//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DNU_ParabiliaProcesoCortes.com.mysuitetest.www {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FactWSFrontSoap", Namespace="http://www.fact.com.mx/schema/ws")]
    public partial class FactWSFront : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback RequestTransactionOperationCompleted;
        
        private System.Threading.SendOrPostCallback SSLTransactionOperationCompleted;
        
        private System.Threading.SendOrPostCallback SecureTransactionOperationCompleted;
        
        private System.Threading.SendOrPostCallback MySuiteTransactionOperationCompleted;
        
        private System.Threading.SendOrPostCallback AuthenticateOperationCompleted;
        
        private System.Threading.SendOrPostCallback AuthenticateFielOperationCompleted;
        
        private System.Threading.SendOrPostCallback AuthenticateWTransformOperationCompleted;
        
        private System.Threading.SendOrPostCallback JsonServiceCallOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FactWSFront() {
            this.Url = global::DNU_ParabiliaProcesoCortes.Properties.Settings.Default.DNU_ParabiliaProcesoCortes_com_mysuitetest_www_FactWSFront;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event RequestTransactionCompletedEventHandler RequestTransactionCompleted;
        
        /// <remarks/>
        public event SSLTransactionCompletedEventHandler SSLTransactionCompleted;
        
        /// <remarks/>
        public event SecureTransactionCompletedEventHandler SecureTransactionCompleted;
        
        /// <remarks/>
        public event MySuiteTransactionCompletedEventHandler MySuiteTransactionCompleted;
        
        /// <remarks/>
        public event AuthenticateCompletedEventHandler AuthenticateCompleted;
        
        /// <remarks/>
        public event AuthenticateFielCompletedEventHandler AuthenticateFielCompleted;
        
        /// <remarks/>
        public event AuthenticateWTransformCompletedEventHandler AuthenticateWTransformCompleted;
        
        /// <remarks/>
        public event JsonServiceCallCompletedEventHandler JsonServiceCallCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.fact.com.mx/schema/ws/RequestTransaction", RequestNamespace="http://www.fact.com.mx/schema/ws", ResponseNamespace="http://www.fact.com.mx/schema/ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TransactionTag RequestTransaction(string Requestor, string Transaction, string Country, string Entity, string User, string UserName, string Data1, string Data2, string Data3) {
            object[] results = this.Invoke("RequestTransaction", new object[] {
                        Requestor,
                        Transaction,
                        Country,
                        Entity,
                        User,
                        UserName,
                        Data1,
                        Data2,
                        Data3});
            return ((TransactionTag)(results[0]));
        }
        
        /// <remarks/>
        public void RequestTransactionAsync(string Requestor, string Transaction, string Country, string Entity, string User, string UserName, string Data1, string Data2, string Data3) {
            this.RequestTransactionAsync(Requestor, Transaction, Country, Entity, User, UserName, Data1, Data2, Data3, null);
        }
        
        /// <remarks/>
        public void RequestTransactionAsync(string Requestor, string Transaction, string Country, string Entity, string User, string UserName, string Data1, string Data2, string Data3, object userState) {
            if ((this.RequestTransactionOperationCompleted == null)) {
                this.RequestTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRequestTransactionOperationCompleted);
            }
            this.InvokeAsync("RequestTransaction", new object[] {
                        Requestor,
                        Transaction,
                        Country,
                        Entity,
                        User,
                        UserName,
                        Data1,
                        Data2,
                        Data3}, this.RequestTransactionOperationCompleted, userState);
        }
        
        private void OnRequestTransactionOperationCompleted(object arg) {
            if ((this.RequestTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RequestTransactionCompleted(this, new RequestTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.fact.com.mx/schema/ws/SSLTransaction", RequestNamespace="http://www.fact.com.mx/schema/ws", ResponseNamespace="http://www.fact.com.mx/schema/ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SSLTransaction(string Entity, string Transaction, string DataExchange) {
            object[] results = this.Invoke("SSLTransaction", new object[] {
                        Entity,
                        Transaction,
                        DataExchange});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SSLTransactionAsync(string Entity, string Transaction, string DataExchange) {
            this.SSLTransactionAsync(Entity, Transaction, DataExchange, null);
        }
        
        /// <remarks/>
        public void SSLTransactionAsync(string Entity, string Transaction, string DataExchange, object userState) {
            if ((this.SSLTransactionOperationCompleted == null)) {
                this.SSLTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSSLTransactionOperationCompleted);
            }
            this.InvokeAsync("SSLTransaction", new object[] {
                        Entity,
                        Transaction,
                        DataExchange}, this.SSLTransactionOperationCompleted, userState);
        }
        
        private void OnSSLTransactionOperationCompleted(object arg) {
            if ((this.SSLTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SSLTransactionCompleted(this, new SSLTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.fact.com.mx/schema/ws/SecureTransaction", RequestNamespace="http://www.fact.com.mx/schema/ws", ResponseNamespace="http://www.fact.com.mx/schema/ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SecureTransaction(string Entity, string Transaction, string DataExchange) {
            object[] results = this.Invoke("SecureTransaction", new object[] {
                        Entity,
                        Transaction,
                        DataExchange});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SecureTransactionAsync(string Entity, string Transaction, string DataExchange) {
            this.SecureTransactionAsync(Entity, Transaction, DataExchange, null);
        }
        
        /// <remarks/>
        public void SecureTransactionAsync(string Entity, string Transaction, string DataExchange, object userState) {
            if ((this.SecureTransactionOperationCompleted == null)) {
                this.SecureTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSecureTransactionOperationCompleted);
            }
            this.InvokeAsync("SecureTransaction", new object[] {
                        Entity,
                        Transaction,
                        DataExchange}, this.SecureTransactionOperationCompleted, userState);
        }
        
        private void OnSecureTransactionOperationCompleted(object arg) {
            if ((this.SecureTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SecureTransactionCompleted(this, new SecureTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.fact.com.mx/schema/ws/MySuiteTransaction", RequestNamespace="http://www.fact.com.mx/schema/ws", ResponseNamespace="http://www.fact.com.mx/schema/ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string MySuiteTransaction(string Entity, string Transaction, string DataExchange, string PrivateData) {
            object[] results = this.Invoke("MySuiteTransaction", new object[] {
                        Entity,
                        Transaction,
                        DataExchange,
                        PrivateData});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void MySuiteTransactionAsync(string Entity, string Transaction, string DataExchange, string PrivateData) {
            this.MySuiteTransactionAsync(Entity, Transaction, DataExchange, PrivateData, null);
        }
        
        /// <remarks/>
        public void MySuiteTransactionAsync(string Entity, string Transaction, string DataExchange, string PrivateData, object userState) {
            if ((this.MySuiteTransactionOperationCompleted == null)) {
                this.MySuiteTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMySuiteTransactionOperationCompleted);
            }
            this.InvokeAsync("MySuiteTransaction", new object[] {
                        Entity,
                        Transaction,
                        DataExchange,
                        PrivateData}, this.MySuiteTransactionOperationCompleted, userState);
        }
        
        private void OnMySuiteTransactionOperationCompleted(object arg) {
            if ((this.MySuiteTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MySuiteTransactionCompleted(this, new MySuiteTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.fact.com.mx/schema/ws/Authenticate", RequestNamespace="http://www.fact.com.mx/schema/ws", ResponseNamespace="http://www.fact.com.mx/schema/ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Authenticate(string taxID, string user, string pass) {
            object[] results = this.Invoke("Authenticate", new object[] {
                        taxID,
                        user,
                        pass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AuthenticateAsync(string taxID, string user, string pass) {
            this.AuthenticateAsync(taxID, user, pass, null);
        }
        
        /// <remarks/>
        public void AuthenticateAsync(string taxID, string user, string pass, object userState) {
            if ((this.AuthenticateOperationCompleted == null)) {
                this.AuthenticateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthenticateOperationCompleted);
            }
            this.InvokeAsync("Authenticate", new object[] {
                        taxID,
                        user,
                        pass}, this.AuthenticateOperationCompleted, userState);
        }
        
        private void OnAuthenticateOperationCompleted(object arg) {
            if ((this.AuthenticateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthenticateCompleted(this, new AuthenticateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.fact.com.mx/schema/ws/AuthenticateFiel", RequestNamespace="http://www.fact.com.mx/schema/ws", ResponseNamespace="http://www.fact.com.mx/schema/ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AuthenticateFiel(string taxID, string fielCert, string fielKey, string fielPass) {
            object[] results = this.Invoke("AuthenticateFiel", new object[] {
                        taxID,
                        fielCert,
                        fielKey,
                        fielPass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AuthenticateFielAsync(string taxID, string fielCert, string fielKey, string fielPass) {
            this.AuthenticateFielAsync(taxID, fielCert, fielKey, fielPass, null);
        }
        
        /// <remarks/>
        public void AuthenticateFielAsync(string taxID, string fielCert, string fielKey, string fielPass, object userState) {
            if ((this.AuthenticateFielOperationCompleted == null)) {
                this.AuthenticateFielOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthenticateFielOperationCompleted);
            }
            this.InvokeAsync("AuthenticateFiel", new object[] {
                        taxID,
                        fielCert,
                        fielKey,
                        fielPass}, this.AuthenticateFielOperationCompleted, userState);
        }
        
        private void OnAuthenticateFielOperationCompleted(object arg) {
            if ((this.AuthenticateFielCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthenticateFielCompleted(this, new AuthenticateFielCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.fact.com.mx/schema/ws/AuthenticateWTransform", RequestNamespace="http://www.fact.com.mx/schema/ws", ResponseNamespace="http://www.fact.com.mx/schema/ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AuthenticateWTransform(string taxID, string user, string pass) {
            object[] results = this.Invoke("AuthenticateWTransform", new object[] {
                        taxID,
                        user,
                        pass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AuthenticateWTransformAsync(string taxID, string user, string pass) {
            this.AuthenticateWTransformAsync(taxID, user, pass, null);
        }
        
        /// <remarks/>
        public void AuthenticateWTransformAsync(string taxID, string user, string pass, object userState) {
            if ((this.AuthenticateWTransformOperationCompleted == null)) {
                this.AuthenticateWTransformOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthenticateWTransformOperationCompleted);
            }
            this.InvokeAsync("AuthenticateWTransform", new object[] {
                        taxID,
                        user,
                        pass}, this.AuthenticateWTransformOperationCompleted, userState);
        }
        
        private void OnAuthenticateWTransformOperationCompleted(object arg) {
            if ((this.AuthenticateWTransformCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthenticateWTransformCompleted(this, new AuthenticateWTransformCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.fact.com.mx/schema/ws/JsonServiceCall", RequestNamespace="http://www.fact.com.mx/schema/ws", ResponseNamespace="http://www.fact.com.mx/schema/ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string JsonServiceCall(string jsonData, string transactionName, string token) {
            object[] results = this.Invoke("JsonServiceCall", new object[] {
                        jsonData,
                        transactionName,
                        token});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void JsonServiceCallAsync(string jsonData, string transactionName, string token) {
            this.JsonServiceCallAsync(jsonData, transactionName, token, null);
        }
        
        /// <remarks/>
        public void JsonServiceCallAsync(string jsonData, string transactionName, string token, object userState) {
            if ((this.JsonServiceCallOperationCompleted == null)) {
                this.JsonServiceCallOperationCompleted = new System.Threading.SendOrPostCallback(this.OnJsonServiceCallOperationCompleted);
            }
            this.InvokeAsync("JsonServiceCall", new object[] {
                        jsonData,
                        transactionName,
                        token}, this.JsonServiceCallOperationCompleted, userState);
        }
        
        private void OnJsonServiceCallOperationCompleted(object arg) {
            if ((this.JsonServiceCallCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.JsonServiceCallCompleted(this, new JsonServiceCallCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fact.com.mx/schema/ws")]
    public partial class TransactionTag {
        
        private FactRequest requestField;
        
        private FactResponse responseField;
        
        private FactResponseData responseDataField;
        
        /// <remarks/>
        public FactRequest Request {
            get {
                return this.requestField;
            }
            set {
                this.requestField = value;
            }
        }
        
        /// <remarks/>
        public FactResponse Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        public FactResponseData ResponseData {
            get {
                return this.responseDataField;
            }
            set {
                this.responseDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fact.com.mx/schema/ws")]
    public partial class FactRequest {
        
        private System.Guid requestorField;
        
        private string requestorNameField;
        
        private bool requestorActiveField;
        
        private Transactions transactionField;
        
        private string countryField;
        
        private string entityField;
        
        private System.Guid userField;
        
        private string userNameField;
        
        private System.Guid idField;
        
        private System.DateTime timeStampField;
        
        /// <remarks/>
        public System.Guid Requestor {
            get {
                return this.requestorField;
            }
            set {
                this.requestorField = value;
            }
        }
        
        /// <remarks/>
        public string RequestorName {
            get {
                return this.requestorNameField;
            }
            set {
                this.requestorNameField = value;
            }
        }
        
        /// <remarks/>
        public bool RequestorActive {
            get {
                return this.requestorActiveField;
            }
            set {
                this.requestorActiveField = value;
            }
        }
        
        /// <remarks/>
        public Transactions Transaction {
            get {
                return this.transactionField;
            }
            set {
                this.transactionField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string Entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public System.Guid Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fact.com.mx/schema/ws")]
    public enum Transactions {
        
        /// <remarks/>
        BASE,
        
        /// <remarks/>
        NO_TRANSACTION,
        
        /// <remarks/>
        CONVERT_NATIVE_XML,
        
        /// <remarks/>
        GET_MTE_BATCH,
        
        /// <remarks/>
        PROCESS_BATCH,
        
        /// <remarks/>
        SYSTEM_REQUEST,
        
        /// <remarks/>
        RECEIVE_BATCH,
        
        /// <remarks/>
        ENROLL_CERT,
        
        /// <remarks/>
        GET_XML,
        
        /// <remarks/>
        GET_HTML,
        
        /// <remarks/>
        GET_XML_AND_HTML,
        
        /// <remarks/>
        CANCEL_XML,
        
        /// <remarks/>
        MARK_XML_AS_PAID,
        
        /// <remarks/>
        MARK_XML_AS_UNPAID,
        
        /// <remarks/>
        SEARCH_BASIC,
        
        /// <remarks/>
        GET_MONTHLY_REPORT,
        
        /// <remarks/>
        GET_MONTHLY_REPORT_FOR_PROVIDER,
        
        /// <remarks/>
        GET_FOLIOS_BY_RFC,
        
        /// <remarks/>
        DOES_ASSIGNMENT_EXIST,
        
        /// <remarks/>
        CANCEL_XML_BY_INTERNAL_ID,
        
        /// <remarks/>
        ACTIVATE_ASSIGNMENT,
        
        /// <remarks/>
        COUNT_ACTIVE_ASSIGNMENTS,
        
        /// <remarks/>
        GET_DOCUMENT,
        
        /// <remarks/>
        GET_DOCUMENT_RETENCIONES,
        
        /// <remarks/>
        AUTHENTICATE_USER,
        
        /// <remarks/>
        GET_ACCOUNT,
        
        /// <remarks/>
        DISTRIBUTE,
        
        /// <remarks/>
        QUEUE_FOR_DISTRIBUTION,
        
        /// <remarks/>
        GET_EFFECTIVE_RIGHTS,
        
        /// <remarks/>
        EXEC_STORED_PROC,
        
        /// <remarks/>
        GET_USER_INFO,
        
        /// <remarks/>
        RECEIVE,
        
        /// <remarks/>
        GET_PREVIEW,
        
        /// <remarks/>
        RETRIEVE_DOCUMENT,
        
        /// <remarks/>
        MARK_DOCUMENT_AS_PAID,
        
        /// <remarks/>
        MARK_DOCUMENT_AS_NOT_PAID,
        
        /// <remarks/>
        CANCEL_DOCUMENT,
        
        /// <remarks/>
        MARK_DOCUMENT_AS_DELETED,
        
        /// <remarks/>
        MARK_DOCUMENT_AS_NOT_DELETED,
        
        /// <remarks/>
        MARK_DOCUMENT_AS_CANCELLED,
        
        /// <remarks/>
        MARK_DOCUMENT_AS_NOT_CANCELLED,
        
        /// <remarks/>
        GET_ADDENDA_RECEIVERS,
        
        /// <remarks/>
        REQUEST_PASSWORD_CHANGE,
        
        /// <remarks/>
        CHANGE_DOCUMENT_SUCURSAL,
        
        /// <remarks/>
        CREATE_ACCOUNT_AS_OWNER,
        
        /// <remarks/>
        CREATE_PASSWORD,
        
        /// <remarks/>
        PASSWORD_FORGOT,
        
        /// <remarks/>
        CREATE_USER,
        
        /// <remarks/>
        INCREMENT_BUNDLE_SIZE,
        
        /// <remarks/>
        TIMBRAR,
        
        /// <remarks/>
        LOOKUP_ISSUED_INTERNAL_ID,
        
        /// <remarks/>
        VALIDATE_CERT,
        
        /// <remarks/>
        BATCH_SERIAL_OPERATIONS,
        
        /// <remarks/>
        PROCESS_LCO,
        
        /// <remarks/>
        ENROLL_THIRD_PARTY_CERT,
        
        /// <remarks/>
        CANCEL_CFDI,
        
        /// <remarks/>
        UPDATE_ACCOUNT_DATA,
        
        /// <remarks/>
        ASSIGN_ACCOUNT_REQUESTOR,
        
        /// <remarks/>
        UPDATE_USER_DATA,
        
        /// <remarks/>
        UPDATE_ADMIN_USER_DATA,
        
        /// <remarks/>
        CREATE_ADMIN_USER,
        
        /// <remarks/>
        UPSERT_GRAPHIC_REPRESENTATION,
        
        /// <remarks/>
        LOOKUP_ISSUED_BATCH_AND_SERIAL,
        
        /// <remarks/>
        CREATE_TIMBRAR_ACCOUNT,
        
        /// <remarks/>
        CREATE_TIMBRAR_ISSUER_ACCOUNT,
        
        /// <remarks/>
        LOOKUP_GUATEMALIAN_ISSUED,
        
        /// <remarks/>
        CLOSE_MONTH,
        
        /// <remarks/>
        SYSTEM_REQUEST1,
        
        /// <remarks/>
        GET_ACUSE,
        
        /// <remarks/>
        GRAPH_REQUEST,
        
        /// <remarks/>
        CANCEL_SINGLE_CFDI,
        
        /// <remarks/>
        CONFIG_REFRESH,
        
        /// <remarks/>
        GET_TIMBRAR_ACCOUNT,
        
        /// <remarks/>
        GET_TIMBRAR_ISSUER_ACCOUNTS,
        
        /// <remarks/>
        CONTRACT_ACCEPTANCE,
        
        /// <remarks/>
        CREATE_FACT_RENEWAL,
        
        /// <remarks/>
        CREATE_TIMB_RENEWAL,
        
        /// <remarks/>
        DELETE_FACT_RENEWAL,
        
        /// <remarks/>
        DELETE_TIMB_RENEWAL,
        
        /// <remarks/>
        MODIFY_FACT_RENEWAL,
        
        /// <remarks/>
        MODIFY_TIMB_RENEWAL,
        
        /// <remarks/>
        RECOVER_FACT_RENEWAL,
        
        /// <remarks/>
        RECOVER_TIMB_RENEWAL,
        
        /// <remarks/>
        SELECT_FACT_RENEWAL,
        
        /// <remarks/>
        SELECT_TIMB_RENEWAL,
        
        /// <remarks/>
        PREINVOICE_SELECT,
        
        /// <remarks/>
        PREINVOICE_DELETE,
        
        /// <remarks/>
        PREINVOICE_UPSERT,
        
        /// <remarks/>
        VALIDATE_DOCUMENT,
        
        /// <remarks/>
        ACTIVATE_ACCOUNT,
        
        /// <remarks/>
        INACTIVATE_ACCOUNT,
        
        /// <remarks/>
        DELETE_ACCOUNT,
        
        /// <remarks/>
        ACTIVATE_TIMBRAR_ACCOUNT,
        
        /// <remarks/>
        INACTIVATE_TIMBRAR_ACCOUNT,
        
        /// <remarks/>
        DELETE_TIMBRAR_ACCOUNT,
        
        /// <remarks/>
        GET_ACCOUNTS_CHANGES,
        
        /// <remarks/>
        GET_TIMBRAR_ACCOUNTS_CHANGES,
        
        /// <remarks/>
        GET_ACCOUNTSSALES_CHANGES,
        
        /// <remarks/>
        GET_TIMBRAR_ACCOUNTSSALES_CHANGES,
        
        /// <remarks/>
        SET_PASS_POLICY,
        
        /// <remarks/>
        RECEIVE_EX,
        
        /// <remarks/>
        VALIDATE_DOCUMENT_EX,
        
        /// <remarks/>
        RETRIEVE_OBSERVATIONS,
        
        /// <remarks/>
        TIMBRAR_RETENCIONES,
        
        /// <remarks/>
        TIMBRAR_RETENCION,
        
        /// <remarks/>
        CANCEL_SINGLE_RETENCIONES,
        
        /// <remarks/>
        CANCEL_SINGLE_RETENCION,
        
        /// <remarks/>
        CANCELAR_RETENCION,
        
        /// <remarks/>
        FIRMAR_RETENCION,
        
        /// <remarks/>
        END_SESSION_LOG,
        
        /// <remarks/>
        CANCELAR_RETENCION_MYSUITE,
        
        /// <remarks/>
        CANCELAR_RETENCION_SINGLE_MYSUITE,
        
        /// <remarks/>
        AUTHENTICATE,
        
        /// <remarks/>
        GET_WEB_SCREEN_MAINFRAME,
        
        /// <remarks/>
        GET_HOME_CONTENT,
        
        /// <remarks/>
        OBTAIN_TEMPLATE,
        
        /// <remarks/>
        GET_USER_CREDENTIALS_HTML,
        
        /// <remarks/>
        OBTAIN_TEMPLATE_COUNT,
        
        /// <remarks/>
        RETRIEVE_DOCUMENT_HTML,
        
        /// <remarks/>
        GET_DOC_DETAILS,
        
        /// <remarks/>
        CANCEL_XML_BATCH,
        
        /// <remarks/>
        GET_REPORTS,
        
        /// <remarks/>
        GET_REPORT_DATA,
        
        /// <remarks/>
        EXECUTE_REPORT,
        
        /// <remarks/>
        PAY_XML,
        
        /// <remarks/>
        PAY_XML_BATCH,
        
        /// <remarks/>
        REDISTRIBUTE,
        
        /// <remarks/>
        GET_EXCEL_LIST,
        
        /// <remarks/>
        OBTAIN_TEMPLATE_CONFIG,
        
        /// <remarks/>
        OBTAIN_TEMPLATE_FOR_PAYMENT,
        
        /// <remarks/>
        USER_FORGOT,
        
        /// <remarks/>
        GET_CLIENT_LIST,
        
        /// <remarks/>
        GET_CLIENT_COUNT,
        
        /// <remarks/>
        GET_BRANCH_LIST,
        
        /// <remarks/>
        GET_BRANCH_COUNT,
        
        /// <remarks/>
        SEND_XML_MAIL,
        
        /// <remarks/>
        GET_PAYMENTS,
        
        /// <remarks/>
        DELETE_PAYMENT,
        
        /// <remarks/>
        GET_FISCAL_DATA,
        
        /// <remarks/>
        SAVE_TEMPLATE_CONFIG,
        
        /// <remarks/>
        UPSERT_BANK_ACCOUNTS,
        
        /// <remarks/>
        DELETE_BANK_ACCOUNTS,
        
        /// <remarks/>
        GET_USER_CREDENTIALS,
        
        /// <remarks/>
        UPSERT_BRANCH,
        
        /// <remarks/>
        INSERT_FISCAL_R,
        
        /// <remarks/>
        UPDATE_FISCAL_R,
        
        /// <remarks/>
        REMOVE_FISCAL_R,
        
        /// <remarks/>
        RETRIEVE_ALL_FISCAL_R,
        
        /// <remarks/>
        UPSERT_CLIENT,
        
        /// <remarks/>
        DELETE_CLIENT,
        
        /// <remarks/>
        GET_DESTINATION_LIST,
        
        /// <remarks/>
        GET_DESTINATION_COUNT,
        
        /// <remarks/>
        UPSERT_DESTINATION,
        
        /// <remarks/>
        UPSERT_FISCAL_DATA,
        
        /// <remarks/>
        GET_EMPLOYEE_LIST,
        
        /// <remarks/>
        GET_EMPLOYEE_COUNT,
        
        /// <remarks/>
        UPSERT_EMPLOYEE,
        
        /// <remarks/>
        DELETE_EMPLOYEE,
        
        /// <remarks/>
        GET_ASSOCIATED_ACCOUNTS_LIST,
        
        /// <remarks/>
        GET_ASSOCIATED_ACCOUNTS_COUNT,
        
        /// <remarks/>
        SET_ACCOUNT_ACTIVE_STATUS,
        
        /// <remarks/>
        GET_ACCOUNT_DATA,
        
        /// <remarks/>
        GET_ACCOUNT_RENEW_INFO,
        
        /// <remarks/>
        GET_ACCOUNT_SERIAL_INFO,
        
        /// <remarks/>
        GET_ACCOUNT_CERT_INFO,
        
        /// <remarks/>
        GET_ACCOUNT_USER_LIST,
        
        /// <remarks/>
        GET_ACCOUNT_USER_COUNT,
        
        /// <remarks/>
        GET_ACCOUNT_BRANCH_ASSIGNMENT_LIST,
        
        /// <remarks/>
        GET_ACCOUNT_BRANCH_ASSIGNMENT_COUNT,
        
        /// <remarks/>
        GET_ACCOUNT_BY_OWNER,
        
        /// <remarks/>
        CREATE_ACCOUNT,
        
        /// <remarks/>
        GET_CLIENT_LIST_AUTOCOMPLETE,
        
        /// <remarks/>
        GET_BRANCH_LIST_AUTOCOMPLETE,
        
        /// <remarks/>
        GET_DESTINATION_LIST_AUTOCOMPLETE,
        
        /// <remarks/>
        GET_CLIENT_BY_ID,
        
        /// <remarks/>
        GET_BRANCH_BY_ID,
        
        /// <remarks/>
        GET_DESTINATION_BY_ID,
        
        /// <remarks/>
        GET_PRODUCT_LIST,
        
        /// <remarks/>
        GET_PRODUCT_COUNT,
        
        /// <remarks/>
        GET_PRODUCT_LIST_AUTOCOMPLETE,
        
        /// <remarks/>
        GET_PRODUCT_BY_ID,
        
        /// <remarks/>
        DELETE_PRODUCT,
        
        /// <remarks/>
        UPSERT_PRODUCT,
        
        /// <remarks/>
        CHANGE_USER_PASSWORD,
        
        /// <remarks/>
        GET_FACTS,
        
        /// <remarks/>
        GET_FACTS_COUNT,
        
        /// <remarks/>
        RETRIEVE_BANK_ACCOUNT,
        
        /// <remarks/>
        AMOUNT_TO_STRING,
        
        /// <remarks/>
        MARK_DOCUMENTS_AS_READ,
        
        /// <remarks/>
        GET_UNREAD_COUNT,
        
        /// <remarks/>
        GET_PAYMENTS_JSON,
        
        /// <remarks/>
        CONVERT_NATIVE_XML_HTML,
        
        /// <remarks/>
        MARK_DOCUMENTS_AS_READ_HTML,
        
        /// <remarks/>
        GET_UNREAD_COUNT_HTML,
        
        /// <remarks/>
        GET_ACUSE_RETENCIONES,
        
        /// <remarks/>
        CANCEL_XML_HTML,
        
        /// <remarks/>
        GET_ACCOUNT_INFO,
        
        /// <remarks/>
        PROCESA_FACTURAS,
        
        /// <remarks/>
        PROCESA_NOMINA,
        
        /// <remarks/>
        DOCUMENT_ZIP,
        
        /// <remarks/>
        AUTHENTICATE_FIEL,
        
        /// <remarks/>
        UPDATE_ACCOUNT_OWNER,
        
        /// <remarks/>
        GET_REQUEST_QUEUE,
        
        /// <remarks/>
        CREATE_REQUEST_QUEUE,
        
        /// <remarks/>
        UPDATE_REQUEST_QUEUE,
        
        /// <remarks/>
        PROCESS_REQUEST_QUEUE,
        
        /// <remarks/>
        DELETE_REQUEST_QUEUE,
        
        /// <remarks/>
        GET_LINK_QUEUE,
        
        /// <remarks/>
        GET_REQUEST_QUEUE_COUNT,
        
        /// <remarks/>
        GET_CATALOG_LIST_AUTOCOMPLETE,
        
        /// <remarks/>
        GET_CATALOG_By_ID,
        
        /// <remarks/>
        FIRMAR_CONTRATO,
        
        /// <remarks/>
        VALIDAR_COMPLEMENTO,
        
        /// <remarks/>
        GET_TAXID_LIST_AUTOCOMPLETE,
        
        /// <remarks/>
        GET_CLAVEPRODSERV_LIST_AUTOCOMPLETE,
        
        /// <remarks/>
        GET_CLAVEPRODSERV_BY_ID,
        
        /// <remarks/>
        GET_CLAVEUNIDAD_LIST_AUTOCOMPLETE,
        
        /// <remarks/>
        GET_CLAVEUNIDAD_BY_ID,
        
        /// <remarks/>
        SOLICITAR_CONFIRMACION,
        
        /// <remarks/>
        GET_PREINVOICES_BY_ID,
        
        /// <remarks/>
        RECUPERAR_CLAVE_CONFIRMACION,
        
        /// <remarks/>
        GET_PREVIEW_HTML,
        
        /// <remarks/>
        RETRIEVE_DOCUMENT_HTML_FORMATS,
        
        /// <remarks/>
        LOOKUP_ISSUED_INTERNAL_ID_HTML,
        
        /// <remarks/>
        PREINVOICE_UPSERT_HTML,
        
        /// <remarks/>
        GET_ACUSE_CANCEL,
        
        /// <remarks/>
        RETRIEVE_LCO_INFO,
        
        /// <remarks/>
        GET_ALERT_CLIENTS_LIST,
        
        /// <remarks/>
        GET_ALERT_CLIENTS_LIST_TIMBRADO,
        
        /// <remarks/>
        GET_GLOBAL_DESTINATARIES,
        
        /// <remarks/>
        CANCEL_XML_JSON,
        
        /// <remarks/>
        GET_PRIMERA_PETICION,
        
        /// <remarks/>
        DELETE_PETICIONES,
        
        /// <remarks/>
        UPDATE_PETICION,
        
        /// <remarks/>
        DELETE_LIGAS,
        
        /// <remarks/>
        GET_DOCUMENTS_DATA,
        
        /// <remarks/>
        GET_TIMBRAR_ACCOUNT_INFO,
        
        /// <remarks/>
        SEARCH_SAT_CATALOGS,
        
        /// <remarks/>
        SEARCH_SAT_CATALOGS_V2,
        
        /// <remarks/>
        SEARCH_SAT_CATALOGS_HTML,
        
        /// <remarks/>
        SEARCH_SAT_CATALOGS_V2_HTML,
        
        /// <remarks/>
        UPDATE_USER_DATA_HTML,
        
        /// <remarks/>
        GET_USERS_HTML,
        
        /// <remarks/>
        LOOKUP_ISSUED_YEAR_BATCH_AND_SERIAL,
        
        /// <remarks/>
        VALIDATE_RFC_IN_LRFC,
        
        /// <remarks/>
        CANCEL_DOCUMENT_2,
        
        /// <remarks/>
        CANCEL_SINGLE_CFDI_2,
        
        /// <remarks/>
        OBTENER_PERMISOS_HTML,
        
        /// <remarks/>
        CONSULTAR_DOCUMENTO,
        
        /// <remarks/>
        CONSULT_DOCUMENT,
        
        /// <remarks/>
        CONSULTAR_DOCUMENTO_TIMBRADO,
        
        /// <remarks/>
        CONSULT_TIMBRAR_DOCUMENT,
        
        /// <remarks/>
        OBTENER_PETICIONES_PENDIENTES,
        
        /// <remarks/>
        GET_PENDING_REQUESTS,
        
        /// <remarks/>
        OBTENER_DOCUMENTOS_RELACIONADOS,
        
        /// <remarks/>
        GET_RELATED_DOCUMENTS,
        
        /// <remarks/>
        PROCESAR_PETICIONES,
        
        /// <remarks/>
        PROCESS_REQUESTS,
        
        /// <remarks/>
        CANCEL_CFDI_2,
        
        /// <remarks/>
        CANCEL_XML_JSON_2,
        
        /// <remarks/>
        CONSULT_DOCUMENT_JSON,
        
        /// <remarks/>
        GET_UNREAD_CANCEL_ALERTS_COUNT,
        
        /// <remarks/>
        GET_UNREAD_CANCEL_ALERTS,
        
        /// <remarks/>
        MARK_UNREAD_CANCEL_ALERT_AS_READ,
        
        /// <remarks/>
        UPDATE_ACCOUNTS_OWNER,
        
        /// <remarks/>
        LOGOUT,
        
        /// <remarks/>
        ASYNC_CONVERT_NATIVE_XML,
        
        /// <remarks/>
        ASYNC_CONVERT_VERIFY,
        
        /// <remarks/>
        ASYNC_RETRIEVE_DOCUMENT,
        
        /// <remarks/>
        PROCESAR_CANCELACION,
        
        /// <remarks/>
        SAVE_LOGO,
        
        /// <remarks/>
        REGISTRAR_SOLICITUD_DM_SAT,
        
        /// <remarks/>
        RENEW_TOKEN,
        
        /// <remarks/>
        REGISTRAR_SOLICITUD_DM_SAT_HTML,
        
        /// <remarks/>
        OBTENER_LINK_ARCHIVO_DM_SAT_HTML,
        
        /// <remarks/>
        OBTENER_LINK_ARCHIVO_DM_SAT,
        
        /// <remarks/>
        OBTENER_SOLICITUD_DM_SAT_HTML,
        
        /// <remarks/>
        OBTENER_SOLICITUD_DM_SAT,
        
        /// <remarks/>
        OBTENER_LISTA_SOLICITUDES_DM_SAT_HTML,
        
        /// <remarks/>
        OBTENER_LISTA_SOLICITUDES_DM_SAT,
        
        /// <remarks/>
        EXEC_STORED_PROC_JSON,
        
        /// <remarks/>
        PASSWORD_FORGOT_HTML,
        
        /// <remarks/>
        OBTENER_LISTA_ALERTAS_LN_HTML,
        
        /// <remarks/>
        OBTENER_LISTA_ALERTAS_LN,
        
        /// <remarks/>
        CAMBIAR_ESTADO_LEIDA_ALERTA_LN_HTML,
        
        /// <remarks/>
        CAMBIAR_ESTADO_LEIDA_ALERTA_LN,
        
        /// <remarks/>
        OBTENER_INFO_LN_SAT_HTML,
        
        /// <remarks/>
        OBTENER_INFO_LN_SAT,
        
        /// <remarks/>
        SYSTEM_REQUEST2,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fact.com.mx/schema/ws")]
    public partial class FactResponseData {
        
        private string responseData1Field;
        
        private string responseData2Field;
        
        private string responseData3Field;
        
        private System.Data.DataSet responseDataSetField;
        
        /// <remarks/>
        public string ResponseData1 {
            get {
                return this.responseData1Field;
            }
            set {
                this.responseData1Field = value;
            }
        }
        
        /// <remarks/>
        public string ResponseData2 {
            get {
                return this.responseData2Field;
            }
            set {
                this.responseData2Field = value;
            }
        }
        
        /// <remarks/>
        public string ResponseData3 {
            get {
                return this.responseData3Field;
            }
            set {
                this.responseData3Field = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet ResponseDataSet {
            get {
                return this.responseDataSetField;
            }
            set {
                this.responseDataSetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fact.com.mx/schema/ws")]
    public partial class BatchID {
        
        private string batchIdField;
        
        private string batchTimeStampField;
        
        private string batchRequestorCountryField;
        
        private string batchRequestorEntityField;
        
        private string batchPositionField;
        
        /// <remarks/>
        public string BatchId {
            get {
                return this.batchIdField;
            }
            set {
                this.batchIdField = value;
            }
        }
        
        /// <remarks/>
        public string BatchTimeStamp {
            get {
                return this.batchTimeStampField;
            }
            set {
                this.batchTimeStampField = value;
            }
        }
        
        /// <remarks/>
        public string BatchRequestorCountry {
            get {
                return this.batchRequestorCountryField;
            }
            set {
                this.batchRequestorCountryField = value;
            }
        }
        
        /// <remarks/>
        public string BatchRequestorEntity {
            get {
                return this.batchRequestorEntityField;
            }
            set {
                this.batchRequestorEntityField = value;
            }
        }
        
        /// <remarks/>
        public string BatchPosition {
            get {
                return this.batchPositionField;
            }
            set {
                this.batchPositionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fact.com.mx/schema/ws")]
    public partial class DocID {
        
        private string countryField;
        
        private string entityField;
        
        private string fiscalNameField;
        
        private string aYearField;
        
        private string aNumberField;
        
        private string batchField;
        
        private string serialField;
        
        private string documentGUIDField;
        
        private string issuedTimeStampField;
        
        private string enrolledTimeStampField;
        
        private string paidTimeStampField;
        
        private string cancelledTimeStampField;
        
        private string internalIDField;
        
        private string batchIDField;
        
        private string batchTimeStampField;
        
        private string batchRequestorCountryField;
        
        private string batchRequestorEntityField;
        
        private string batchPositionField;
        
        private string receiverCountryField;
        
        private string receiverEntityField;
        
        private string receiverTaxIDField;
        
        private string receiverNameField;
        
        private string claveAgenteField;
        
        private string numeroDePolizaField;
        
        private string currencyField;
        
        private string totalAmountField;
        
        private string type1Field;
        
        private string type2Field;
        
        private string suggestedFileNameField;
        
        private string suggestedFileName2Field;
        
        private string observacionesField;
        
        private string observacionesHtmlField;
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string Entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
            }
        }
        
        /// <remarks/>
        public string FiscalName {
            get {
                return this.fiscalNameField;
            }
            set {
                this.fiscalNameField = value;
            }
        }
        
        /// <remarks/>
        public string AYear {
            get {
                return this.aYearField;
            }
            set {
                this.aYearField = value;
            }
        }
        
        /// <remarks/>
        public string ANumber {
            get {
                return this.aNumberField;
            }
            set {
                this.aNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Batch {
            get {
                return this.batchField;
            }
            set {
                this.batchField = value;
            }
        }
        
        /// <remarks/>
        public string Serial {
            get {
                return this.serialField;
            }
            set {
                this.serialField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentGUID {
            get {
                return this.documentGUIDField;
            }
            set {
                this.documentGUIDField = value;
            }
        }
        
        /// <remarks/>
        public string IssuedTimeStamp {
            get {
                return this.issuedTimeStampField;
            }
            set {
                this.issuedTimeStampField = value;
            }
        }
        
        /// <remarks/>
        public string EnrolledTimeStamp {
            get {
                return this.enrolledTimeStampField;
            }
            set {
                this.enrolledTimeStampField = value;
            }
        }
        
        /// <remarks/>
        public string PaidTimeStamp {
            get {
                return this.paidTimeStampField;
            }
            set {
                this.paidTimeStampField = value;
            }
        }
        
        /// <remarks/>
        public string CancelledTimeStamp {
            get {
                return this.cancelledTimeStampField;
            }
            set {
                this.cancelledTimeStampField = value;
            }
        }
        
        /// <remarks/>
        public string InternalID {
            get {
                return this.internalIDField;
            }
            set {
                this.internalIDField = value;
            }
        }
        
        /// <remarks/>
        public string BatchID {
            get {
                return this.batchIDField;
            }
            set {
                this.batchIDField = value;
            }
        }
        
        /// <remarks/>
        public string BatchTimeStamp {
            get {
                return this.batchTimeStampField;
            }
            set {
                this.batchTimeStampField = value;
            }
        }
        
        /// <remarks/>
        public string BatchRequestorCountry {
            get {
                return this.batchRequestorCountryField;
            }
            set {
                this.batchRequestorCountryField = value;
            }
        }
        
        /// <remarks/>
        public string BatchRequestorEntity {
            get {
                return this.batchRequestorEntityField;
            }
            set {
                this.batchRequestorEntityField = value;
            }
        }
        
        /// <remarks/>
        public string BatchPosition {
            get {
                return this.batchPositionField;
            }
            set {
                this.batchPositionField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiverCountry {
            get {
                return this.receiverCountryField;
            }
            set {
                this.receiverCountryField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiverEntity {
            get {
                return this.receiverEntityField;
            }
            set {
                this.receiverEntityField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiverTaxID {
            get {
                return this.receiverTaxIDField;
            }
            set {
                this.receiverTaxIDField = value;
            }
        }
        
        /// <remarks/>
        public string ReceiverName {
            get {
                return this.receiverNameField;
            }
            set {
                this.receiverNameField = value;
            }
        }
        
        /// <remarks/>
        public string ClaveAgente {
            get {
                return this.claveAgenteField;
            }
            set {
                this.claveAgenteField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroDePoliza {
            get {
                return this.numeroDePolizaField;
            }
            set {
                this.numeroDePolizaField = value;
            }
        }
        
        /// <remarks/>
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        public string TotalAmount {
            get {
                return this.totalAmountField;
            }
            set {
                this.totalAmountField = value;
            }
        }
        
        /// <remarks/>
        public string Type1 {
            get {
                return this.type1Field;
            }
            set {
                this.type1Field = value;
            }
        }
        
        /// <remarks/>
        public string Type2 {
            get {
                return this.type2Field;
            }
            set {
                this.type2Field = value;
            }
        }
        
        /// <remarks/>
        public string SuggestedFileName {
            get {
                return this.suggestedFileNameField;
            }
            set {
                this.suggestedFileNameField = value;
            }
        }
        
        /// <remarks/>
        public string SuggestedFileName2 {
            get {
                return this.suggestedFileName2Field;
            }
            set {
                this.suggestedFileName2Field = value;
            }
        }
        
        /// <remarks/>
        public string Observaciones {
            get {
                return this.observacionesField;
            }
            set {
                this.observacionesField = value;
            }
        }
        
        /// <remarks/>
        public string ObservacionesHtml {
            get {
                return this.observacionesHtmlField;
            }
            set {
                this.observacionesHtmlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.fact.com.mx/schema/ws")]
    public partial class FactResponse {
        
        private bool resultField;
        
        private System.DateTime timeStampField;
        
        private string lastResultField;
        
        private int codeField;
        
        private string descriptionField;
        
        private string hintField;
        
        private string dataField;
        
        private string processorField;
        
        private DocID identifierField;
        
        private BatchID batchIdentifierField;
        
        /// <remarks/>
        public bool Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TimeStamp {
            get {
                return this.timeStampField;
            }
            set {
                this.timeStampField = value;
            }
        }
        
        /// <remarks/>
        public string LastResult {
            get {
                return this.lastResultField;
            }
            set {
                this.lastResultField = value;
            }
        }
        
        /// <remarks/>
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Hint {
            get {
                return this.hintField;
            }
            set {
                this.hintField = value;
            }
        }
        
        /// <remarks/>
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        public string Processor {
            get {
                return this.processorField;
            }
            set {
                this.processorField = value;
            }
        }
        
        /// <remarks/>
        public DocID Identifier {
            get {
                return this.identifierField;
            }
            set {
                this.identifierField = value;
            }
        }
        
        /// <remarks/>
        public BatchID BatchIdentifier {
            get {
                return this.batchIdentifierField;
            }
            set {
                this.batchIdentifierField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void RequestTransactionCompletedEventHandler(object sender, RequestTransactionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RequestTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RequestTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TransactionTag Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TransactionTag)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void SSLTransactionCompletedEventHandler(object sender, SSLTransactionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SSLTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SSLTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void SecureTransactionCompletedEventHandler(object sender, SecureTransactionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SecureTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SecureTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void MySuiteTransactionCompletedEventHandler(object sender, MySuiteTransactionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MySuiteTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MySuiteTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void AuthenticateCompletedEventHandler(object sender, AuthenticateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthenticateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthenticateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void AuthenticateFielCompletedEventHandler(object sender, AuthenticateFielCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthenticateFielCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthenticateFielCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void AuthenticateWTransformCompletedEventHandler(object sender, AuthenticateWTransformCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthenticateWTransformCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthenticateWTransformCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void JsonServiceCallCompletedEventHandler(object sender, JsonServiceCallCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class JsonServiceCallCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal JsonServiceCallCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591