//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18213
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18213.
// 
#pragma warning disable 1591

namespace DIGICEL_ActualizaUsuarios.mx.com.dnu.sitios {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS_AdministracionPortBinding", Namespace="http://Admin/")]
    public partial class WS_Administracion : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ActualizaPasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback GeneraCorteOperadorOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtieneDetallesCorteOperadorOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviaSMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback CentralMovilConsultarUltimaOperacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback CrearEmpleadoClubEscalaOperationCompleted;
        
        private System.Threading.SendOrPostCallback CentralMovilConsultarCortesOperationCompleted;
        
        private System.Threading.SendOrPostCallback CentralMovilObtieneColectivaOperationCompleted;
        
        private System.Threading.SendOrPostCallback CentralMovilCortarOperationCompleted;
        
        private System.Threading.SendOrPostCallback CrearUsuarioShopAndWinOperationCompleted;
        
        private System.Threading.SendOrPostCallback CrearCuentasaEmpleadoClubEscalaOperationCompleted;
        
        private System.Threading.SendOrPostCallback CentralMovilConsultarOperacionesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS_Administracion() {
            this.Url = global::DIGICEL_ActualizaUsuarios.Properties.Settings.Default.DIGICEL_ActualizaUsuarios_mx_com_dnu_sitios_WS_Administracion;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ActualizaPasswordCompletedEventHandler ActualizaPasswordCompleted;
        
        /// <remarks/>
        public event GeneraCorteOperadorCompletedEventHandler GeneraCorteOperadorCompleted;
        
        /// <remarks/>
        public event ObtieneDetallesCorteOperadorCompletedEventHandler ObtieneDetallesCorteOperadorCompleted;
        
        /// <remarks/>
        public event EnviaSMSCompletedEventHandler EnviaSMSCompleted;
        
        /// <remarks/>
        public event CentralMovilConsultarUltimaOperacionCompletedEventHandler CentralMovilConsultarUltimaOperacionCompleted;
        
        /// <remarks/>
        public event CrearEmpleadoClubEscalaCompletedEventHandler CrearEmpleadoClubEscalaCompleted;
        
        /// <remarks/>
        public event CentralMovilConsultarCortesCompletedEventHandler CentralMovilConsultarCortesCompleted;
        
        /// <remarks/>
        public event CentralMovilObtieneColectivaCompletedEventHandler CentralMovilObtieneColectivaCompleted;
        
        /// <remarks/>
        public event CentralMovilCortarCompletedEventHandler CentralMovilCortarCompleted;
        
        /// <remarks/>
        public event CrearUsuarioShopAndWinCompletedEventHandler CrearUsuarioShopAndWinCompleted;
        
        /// <remarks/>
        public event CrearCuentasaEmpleadoClubEscalaCompletedEventHandler CrearCuentasaEmpleadoClubEscalaCompleted;
        
        /// <remarks/>
        public event CentralMovilConsultarOperacionesCompletedEventHandler CentralMovilConsultarOperacionesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Admin/", ResponseNamespace="http://Admin/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ActualizaPassword([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string password, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ClaveEvento, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ClaveTipoMA, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ClaveMedioAcceso, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string NIPNuevo, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string NIPAnterior) {
            object[] results = this.Invoke("ActualizaPassword", new object[] {
                        usuario,
                        password,
                        ClaveEvento,
                        ClaveTipoMA,
                        ClaveMedioAcceso,
                        NIPNuevo,
                        NIPAnterior});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizaPasswordAsync(string usuario, string password, string ClaveEvento, string ClaveTipoMA, string ClaveMedioAcceso, string NIPNuevo, string NIPAnterior) {
            this.ActualizaPasswordAsync(usuario, password, ClaveEvento, ClaveTipoMA, ClaveMedioAcceso, NIPNuevo, NIPAnterior, null);
        }
        
        /// <remarks/>
        public void ActualizaPasswordAsync(string usuario, string password, string ClaveEvento, string ClaveTipoMA, string ClaveMedioAcceso, string NIPNuevo, string NIPAnterior, object userState) {
            if ((this.ActualizaPasswordOperationCompleted == null)) {
                this.ActualizaPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizaPasswordOperationCompleted);
            }
            this.InvokeAsync("ActualizaPassword", new object[] {
                        usuario,
                        password,
                        ClaveEvento,
                        ClaveTipoMA,
                        ClaveMedioAcceso,
                        NIPNuevo,
                        NIPAnterior}, this.ActualizaPasswordOperationCompleted, userState);
        }
        
        private void OnActualizaPasswordOperationCompleted(object arg) {
            if ((this.ActualizaPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizaPasswordCompleted(this, new ActualizaPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Admin/", ResponseNamespace="http://Admin/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int GeneraCorteOperador([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string password, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ClaveEvento, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ClaveOperador) {
            object[] results = this.Invoke("GeneraCorteOperador", new object[] {
                        usuario,
                        password,
                        ClaveEvento,
                        ClaveOperador});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GeneraCorteOperadorAsync(string usuario, string password, string ClaveEvento, string ClaveOperador) {
            this.GeneraCorteOperadorAsync(usuario, password, ClaveEvento, ClaveOperador, null);
        }
        
        /// <remarks/>
        public void GeneraCorteOperadorAsync(string usuario, string password, string ClaveEvento, string ClaveOperador, object userState) {
            if ((this.GeneraCorteOperadorOperationCompleted == null)) {
                this.GeneraCorteOperadorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGeneraCorteOperadorOperationCompleted);
            }
            this.InvokeAsync("GeneraCorteOperador", new object[] {
                        usuario,
                        password,
                        ClaveEvento,
                        ClaveOperador}, this.GeneraCorteOperadorOperationCompleted, userState);
        }
        
        private void OnGeneraCorteOperadorOperationCompleted(object arg) {
            if ((this.GeneraCorteOperadorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GeneraCorteOperadorCompleted(this, new GeneraCorteOperadorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Admin/", ResponseNamespace="http://Admin/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ObtieneDetallesCorteOperador([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string password, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ClaveEvento, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ClaveOperador, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int TipoReporte) {
            object[] results = this.Invoke("ObtieneDetallesCorteOperador", new object[] {
                        usuario,
                        password,
                        ClaveEvento,
                        ClaveOperador,
                        TipoReporte});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ObtieneDetallesCorteOperadorAsync(string usuario, string password, string ClaveEvento, string ClaveOperador, int TipoReporte) {
            this.ObtieneDetallesCorteOperadorAsync(usuario, password, ClaveEvento, ClaveOperador, TipoReporte, null);
        }
        
        /// <remarks/>
        public void ObtieneDetallesCorteOperadorAsync(string usuario, string password, string ClaveEvento, string ClaveOperador, int TipoReporte, object userState) {
            if ((this.ObtieneDetallesCorteOperadorOperationCompleted == null)) {
                this.ObtieneDetallesCorteOperadorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtieneDetallesCorteOperadorOperationCompleted);
            }
            this.InvokeAsync("ObtieneDetallesCorteOperador", new object[] {
                        usuario,
                        password,
                        ClaveEvento,
                        ClaveOperador,
                        TipoReporte}, this.ObtieneDetallesCorteOperadorOperationCompleted, userState);
        }
        
        private void OnObtieneDetallesCorteOperadorOperationCompleted(object arg) {
            if ((this.ObtieneDetallesCorteOperadorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtieneDetallesCorteOperadorCompleted(this, new ObtieneDetallesCorteOperadorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Admin/", ResponseNamespace="http://Admin/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int EnviaSMS([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string password, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ClaveEvento, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Telefono, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Mensaje) {
            object[] results = this.Invoke("EnviaSMS", new object[] {
                        usuario,
                        password,
                        ClaveEvento,
                        Telefono,
                        Mensaje});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void EnviaSMSAsync(string usuario, string password, string ClaveEvento, string Telefono, string Mensaje) {
            this.EnviaSMSAsync(usuario, password, ClaveEvento, Telefono, Mensaje, null);
        }
        
        /// <remarks/>
        public void EnviaSMSAsync(string usuario, string password, string ClaveEvento, string Telefono, string Mensaje, object userState) {
            if ((this.EnviaSMSOperationCompleted == null)) {
                this.EnviaSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviaSMSOperationCompleted);
            }
            this.InvokeAsync("EnviaSMS", new object[] {
                        usuario,
                        password,
                        ClaveEvento,
                        Telefono,
                        Mensaje}, this.EnviaSMSOperationCompleted, userState);
        }
        
        private void OnEnviaSMSOperationCompleted(object arg) {
            if ((this.EnviaSMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviaSMSCompleted(this, new EnviaSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Admin/", ResponseNamespace="http://Admin/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public operacion CentralMovilConsultarUltimaOperacion([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string password, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ClaveOperador) {
            object[] results = this.Invoke("CentralMovilConsultarUltimaOperacion", new object[] {
                        usuario,
                        password,
                        ClaveOperador});
            return ((operacion)(results[0]));
        }
        
        /// <remarks/>
        public void CentralMovilConsultarUltimaOperacionAsync(string usuario, string password, string ClaveOperador) {
            this.CentralMovilConsultarUltimaOperacionAsync(usuario, password, ClaveOperador, null);
        }
        
        /// <remarks/>
        public void CentralMovilConsultarUltimaOperacionAsync(string usuario, string password, string ClaveOperador, object userState) {
            if ((this.CentralMovilConsultarUltimaOperacionOperationCompleted == null)) {
                this.CentralMovilConsultarUltimaOperacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCentralMovilConsultarUltimaOperacionOperationCompleted);
            }
            this.InvokeAsync("CentralMovilConsultarUltimaOperacion", new object[] {
                        usuario,
                        password,
                        ClaveOperador}, this.CentralMovilConsultarUltimaOperacionOperationCompleted, userState);
        }
        
        private void OnCentralMovilConsultarUltimaOperacionOperationCompleted(object arg) {
            if ((this.CentralMovilConsultarUltimaOperacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CentralMovilConsultarUltimaOperacionCompleted(this, new CentralMovilConsultarUltimaOperacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Admin/", ResponseNamespace="http://Admin/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int CrearEmpleadoClubEscala([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string password, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ClaveEvento, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ClaveTipoColectiva, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ClaveColectivaPadre, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ClaveColectiva, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string NombreORazonSocial, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string APaterno, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string AMaterno, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Movil, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Email, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int ID_CadenaComercial, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Baja) {
            object[] results = this.Invoke("CrearEmpleadoClubEscala", new object[] {
                        usuario,
                        password,
                        ClaveEvento,
                        ClaveTipoColectiva,
                        ClaveColectivaPadre,
                        ClaveColectiva,
                        NombreORazonSocial,
                        APaterno,
                        AMaterno,
                        Movil,
                        Email,
                        ID_CadenaComercial,
                        Baja});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CrearEmpleadoClubEscalaAsync(string usuario, string password, string ClaveEvento, string ClaveTipoColectiva, string ClaveColectivaPadre, string ClaveColectiva, string NombreORazonSocial, string APaterno, string AMaterno, string Movil, string Email, int ID_CadenaComercial, string Baja) {
            this.CrearEmpleadoClubEscalaAsync(usuario, password, ClaveEvento, ClaveTipoColectiva, ClaveColectivaPadre, ClaveColectiva, NombreORazonSocial, APaterno, AMaterno, Movil, Email, ID_CadenaComercial, Baja, null);
        }
        
        /// <remarks/>
        public void CrearEmpleadoClubEscalaAsync(string usuario, string password, string ClaveEvento, string ClaveTipoColectiva, string ClaveColectivaPadre, string ClaveColectiva, string NombreORazonSocial, string APaterno, string AMaterno, string Movil, string Email, int ID_CadenaComercial, string Baja, object userState) {
            if ((this.CrearEmpleadoClubEscalaOperationCompleted == null)) {
                this.CrearEmpleadoClubEscalaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrearEmpleadoClubEscalaOperationCompleted);
            }
            this.InvokeAsync("CrearEmpleadoClubEscala", new object[] {
                        usuario,
                        password,
                        ClaveEvento,
                        ClaveTipoColectiva,
                        ClaveColectivaPadre,
                        ClaveColectiva,
                        NombreORazonSocial,
                        APaterno,
                        AMaterno,
                        Movil,
                        Email,
                        ID_CadenaComercial,
                        Baja}, this.CrearEmpleadoClubEscalaOperationCompleted, userState);
        }
        
        private void OnCrearEmpleadoClubEscalaOperationCompleted(object arg) {
            if ((this.CrearEmpleadoClubEscalaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrearEmpleadoClubEscalaCompleted(this, new CrearEmpleadoClubEscalaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Admin/", ResponseNamespace="http://Admin/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CentralMovilConsultarCortes([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string password, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ClaveOperador) {
            object[] results = this.Invoke("CentralMovilConsultarCortes", new object[] {
                        usuario,
                        password,
                        ClaveOperador});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CentralMovilConsultarCortesAsync(string usuario, string password, string ClaveOperador) {
            this.CentralMovilConsultarCortesAsync(usuario, password, ClaveOperador, null);
        }
        
        /// <remarks/>
        public void CentralMovilConsultarCortesAsync(string usuario, string password, string ClaveOperador, object userState) {
            if ((this.CentralMovilConsultarCortesOperationCompleted == null)) {
                this.CentralMovilConsultarCortesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCentralMovilConsultarCortesOperationCompleted);
            }
            this.InvokeAsync("CentralMovilConsultarCortes", new object[] {
                        usuario,
                        password,
                        ClaveOperador}, this.CentralMovilConsultarCortesOperationCompleted, userState);
        }
        
        private void OnCentralMovilConsultarCortesOperationCompleted(object arg) {
            if ((this.CentralMovilConsultarCortesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CentralMovilConsultarCortesCompleted(this, new CentralMovilConsultarCortesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Admin/", ResponseNamespace="http://Admin/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public colectiva CentralMovilObtieneColectiva([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string password, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ClaveColectiva, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int ID_CadenaComercial) {
            object[] results = this.Invoke("CentralMovilObtieneColectiva", new object[] {
                        usuario,
                        password,
                        ClaveColectiva,
                        ID_CadenaComercial});
            return ((colectiva)(results[0]));
        }
        
        /// <remarks/>
        public void CentralMovilObtieneColectivaAsync(string usuario, string password, string ClaveColectiva, int ID_CadenaComercial) {
            this.CentralMovilObtieneColectivaAsync(usuario, password, ClaveColectiva, ID_CadenaComercial, null);
        }
        
        /// <remarks/>
        public void CentralMovilObtieneColectivaAsync(string usuario, string password, string ClaveColectiva, int ID_CadenaComercial, object userState) {
            if ((this.CentralMovilObtieneColectivaOperationCompleted == null)) {
                this.CentralMovilObtieneColectivaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCentralMovilObtieneColectivaOperationCompleted);
            }
            this.InvokeAsync("CentralMovilObtieneColectiva", new object[] {
                        usuario,
                        password,
                        ClaveColectiva,
                        ID_CadenaComercial}, this.CentralMovilObtieneColectivaOperationCompleted, userState);
        }
        
        private void OnCentralMovilObtieneColectivaOperationCompleted(object arg) {
            if ((this.CentralMovilObtieneColectivaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CentralMovilObtieneColectivaCompleted(this, new CentralMovilObtieneColectivaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Admin/", ResponseNamespace="http://Admin/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CentralMovilCortar([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string password, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ClaveOperador) {
            object[] results = this.Invoke("CentralMovilCortar", new object[] {
                        usuario,
                        password,
                        ClaveOperador});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CentralMovilCortarAsync(string usuario, string password, string ClaveOperador) {
            this.CentralMovilCortarAsync(usuario, password, ClaveOperador, null);
        }
        
        /// <remarks/>
        public void CentralMovilCortarAsync(string usuario, string password, string ClaveOperador, object userState) {
            if ((this.CentralMovilCortarOperationCompleted == null)) {
                this.CentralMovilCortarOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCentralMovilCortarOperationCompleted);
            }
            this.InvokeAsync("CentralMovilCortar", new object[] {
                        usuario,
                        password,
                        ClaveOperador}, this.CentralMovilCortarOperationCompleted, userState);
        }
        
        private void OnCentralMovilCortarOperationCompleted(object arg) {
            if ((this.CentralMovilCortarCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CentralMovilCortarCompleted(this, new CentralMovilCortarCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Admin/", ResponseNamespace="http://Admin/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int CrearUsuarioShopAndWin([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string password, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ClaveColectiva, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string NombreORazonSocial, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string APaterno, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string AMaterno, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Movil, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Email, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string TipoDigicel, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] bool Baja, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlIgnoreAttribute()] bool BajaSpecified) {
            object[] results = this.Invoke("CrearUsuarioShopAndWin", new object[] {
                        usuario,
                        password,
                        ClaveColectiva,
                        NombreORazonSocial,
                        APaterno,
                        AMaterno,
                        Movil,
                        Email,
                        TipoDigicel,
                        Baja,
                        BajaSpecified});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CrearUsuarioShopAndWinAsync(string usuario, string password, string ClaveColectiva, string NombreORazonSocial, string APaterno, string AMaterno, string Movil, string Email, string TipoDigicel, bool Baja, bool BajaSpecified) {
            this.CrearUsuarioShopAndWinAsync(usuario, password, ClaveColectiva, NombreORazonSocial, APaterno, AMaterno, Movil, Email, TipoDigicel, Baja, BajaSpecified, null);
        }
        
        /// <remarks/>
        public void CrearUsuarioShopAndWinAsync(string usuario, string password, string ClaveColectiva, string NombreORazonSocial, string APaterno, string AMaterno, string Movil, string Email, string TipoDigicel, bool Baja, bool BajaSpecified, object userState) {
            if ((this.CrearUsuarioShopAndWinOperationCompleted == null)) {
                this.CrearUsuarioShopAndWinOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrearUsuarioShopAndWinOperationCompleted);
            }
            this.InvokeAsync("CrearUsuarioShopAndWin", new object[] {
                        usuario,
                        password,
                        ClaveColectiva,
                        NombreORazonSocial,
                        APaterno,
                        AMaterno,
                        Movil,
                        Email,
                        TipoDigicel,
                        Baja,
                        BajaSpecified}, this.CrearUsuarioShopAndWinOperationCompleted, userState);
        }
        
        private void OnCrearUsuarioShopAndWinOperationCompleted(object arg) {
            if ((this.CrearUsuarioShopAndWinCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrearUsuarioShopAndWinCompleted(this, new CrearUsuarioShopAndWinCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Admin/", ResponseNamespace="http://Admin/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int CrearCuentasaEmpleadoClubEscala(
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string password, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ClaveEvento, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ClaveTipoColectiva, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ClaveColectivaPadre, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ClaveColectiva, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int ID_Colectiva, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string NombreORazonSocial, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string APaterno, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string AMaterno, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string FechaNacimiento, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Movil, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Email, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ClaveGrupoMA, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string NIP, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int AniosParaExpirarMA, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ClaveGrupoCuenta, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int ID_CadenaComercial, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ClaveTipoCuenta, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string SaldoInicial, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Baja, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string CicloNominal, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string DiaPago) {
            object[] results = this.Invoke("CrearCuentasaEmpleadoClubEscala", new object[] {
                        usuario,
                        password,
                        ClaveEvento,
                        ClaveTipoColectiva,
                        ClaveColectivaPadre,
                        ClaveColectiva,
                        ID_Colectiva,
                        NombreORazonSocial,
                        APaterno,
                        AMaterno,
                        FechaNacimiento,
                        Movil,
                        Email,
                        ClaveGrupoMA,
                        NIP,
                        AniosParaExpirarMA,
                        ClaveGrupoCuenta,
                        ID_CadenaComercial,
                        ClaveTipoCuenta,
                        SaldoInicial,
                        Baja,
                        CicloNominal,
                        DiaPago});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CrearCuentasaEmpleadoClubEscalaAsync(
                    string usuario, 
                    string password, 
                    string ClaveEvento, 
                    string ClaveTipoColectiva, 
                    string ClaveColectivaPadre, 
                    string ClaveColectiva, 
                    int ID_Colectiva, 
                    string NombreORazonSocial, 
                    string APaterno, 
                    string AMaterno, 
                    string FechaNacimiento, 
                    string Movil, 
                    string Email, 
                    string ClaveGrupoMA, 
                    string NIP, 
                    int AniosParaExpirarMA, 
                    string ClaveGrupoCuenta, 
                    int ID_CadenaComercial, 
                    string ClaveTipoCuenta, 
                    string SaldoInicial, 
                    string Baja, 
                    string CicloNominal, 
                    string DiaPago) {
            this.CrearCuentasaEmpleadoClubEscalaAsync(usuario, password, ClaveEvento, ClaveTipoColectiva, ClaveColectivaPadre, ClaveColectiva, ID_Colectiva, NombreORazonSocial, APaterno, AMaterno, FechaNacimiento, Movil, Email, ClaveGrupoMA, NIP, AniosParaExpirarMA, ClaveGrupoCuenta, ID_CadenaComercial, ClaveTipoCuenta, SaldoInicial, Baja, CicloNominal, DiaPago, null);
        }
        
        /// <remarks/>
        public void CrearCuentasaEmpleadoClubEscalaAsync(
                    string usuario, 
                    string password, 
                    string ClaveEvento, 
                    string ClaveTipoColectiva, 
                    string ClaveColectivaPadre, 
                    string ClaveColectiva, 
                    int ID_Colectiva, 
                    string NombreORazonSocial, 
                    string APaterno, 
                    string AMaterno, 
                    string FechaNacimiento, 
                    string Movil, 
                    string Email, 
                    string ClaveGrupoMA, 
                    string NIP, 
                    int AniosParaExpirarMA, 
                    string ClaveGrupoCuenta, 
                    int ID_CadenaComercial, 
                    string ClaveTipoCuenta, 
                    string SaldoInicial, 
                    string Baja, 
                    string CicloNominal, 
                    string DiaPago, 
                    object userState) {
            if ((this.CrearCuentasaEmpleadoClubEscalaOperationCompleted == null)) {
                this.CrearCuentasaEmpleadoClubEscalaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrearCuentasaEmpleadoClubEscalaOperationCompleted);
            }
            this.InvokeAsync("CrearCuentasaEmpleadoClubEscala", new object[] {
                        usuario,
                        password,
                        ClaveEvento,
                        ClaveTipoColectiva,
                        ClaveColectivaPadre,
                        ClaveColectiva,
                        ID_Colectiva,
                        NombreORazonSocial,
                        APaterno,
                        AMaterno,
                        FechaNacimiento,
                        Movil,
                        Email,
                        ClaveGrupoMA,
                        NIP,
                        AniosParaExpirarMA,
                        ClaveGrupoCuenta,
                        ID_CadenaComercial,
                        ClaveTipoCuenta,
                        SaldoInicial,
                        Baja,
                        CicloNominal,
                        DiaPago}, this.CrearCuentasaEmpleadoClubEscalaOperationCompleted, userState);
        }
        
        private void OnCrearCuentasaEmpleadoClubEscalaOperationCompleted(object arg) {
            if ((this.CrearCuentasaEmpleadoClubEscalaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrearCuentasaEmpleadoClubEscalaCompleted(this, new CrearCuentasaEmpleadoClubEscalaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Admin/", ResponseNamespace="http://Admin/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CentralMovilConsultarOperaciones([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string password, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ClaveOperador, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string FechaInicial, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string FechaFinal) {
            object[] results = this.Invoke("CentralMovilConsultarOperaciones", new object[] {
                        usuario,
                        password,
                        ClaveOperador,
                        FechaInicial,
                        FechaFinal});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CentralMovilConsultarOperacionesAsync(string usuario, string password, string ClaveOperador, string FechaInicial, string FechaFinal) {
            this.CentralMovilConsultarOperacionesAsync(usuario, password, ClaveOperador, FechaInicial, FechaFinal, null);
        }
        
        /// <remarks/>
        public void CentralMovilConsultarOperacionesAsync(string usuario, string password, string ClaveOperador, string FechaInicial, string FechaFinal, object userState) {
            if ((this.CentralMovilConsultarOperacionesOperationCompleted == null)) {
                this.CentralMovilConsultarOperacionesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCentralMovilConsultarOperacionesOperationCompleted);
            }
            this.InvokeAsync("CentralMovilConsultarOperaciones", new object[] {
                        usuario,
                        password,
                        ClaveOperador,
                        FechaInicial,
                        FechaFinal}, this.CentralMovilConsultarOperacionesOperationCompleted, userState);
        }
        
        private void OnCentralMovilConsultarOperacionesOperationCompleted(object arg) {
            if ((this.CentralMovilConsultarOperacionesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CentralMovilConsultarOperacionesCompleted(this, new CentralMovilConsultarOperacionesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18213")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Admin/")]
    public partial class operacion {
        
        private string autorizacionField;
        
        private string beneficiarioField;
        
        private string fechaHoraField;
        
        private string importeField;
        
        private string referenciaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string autorizacion {
            get {
                return this.autorizacionField;
            }
            set {
                this.autorizacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string beneficiario {
            get {
                return this.beneficiarioField;
            }
            set {
                this.beneficiarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fechaHora {
            get {
                return this.fechaHoraField;
            }
            set {
                this.fechaHoraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string importe {
            get {
                return this.importeField;
            }
            set {
                this.importeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string referencia {
            get {
                return this.referenciaField;
            }
            set {
                this.referenciaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18213")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Admin/")]
    public partial class colectiva {
        
        private string apellidoMaternoField;
        
        private string apellidoPaternoField;
        
        private string claveColectivaField;
        
        private string iD_CadenaComercialField;
        
        private string iD_ColectivaField;
        
        private string iD_GrupoComercialField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apellidoMaterno {
            get {
                return this.apellidoMaternoField;
            }
            set {
                this.apellidoMaternoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apellidoPaterno {
            get {
                return this.apellidoPaternoField;
            }
            set {
                this.apellidoPaternoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string claveColectiva {
            get {
                return this.claveColectivaField;
            }
            set {
                this.claveColectivaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ID_CadenaComercial {
            get {
                return this.iD_CadenaComercialField;
            }
            set {
                this.iD_CadenaComercialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ID_Colectiva {
            get {
                return this.iD_ColectivaField;
            }
            set {
                this.iD_ColectivaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ID_GrupoComercial {
            get {
                return this.iD_GrupoComercialField;
            }
            set {
                this.iD_GrupoComercialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void ActualizaPasswordCompletedEventHandler(object sender, ActualizaPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizaPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizaPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void GeneraCorteOperadorCompletedEventHandler(object sender, GeneraCorteOperadorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GeneraCorteOperadorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GeneraCorteOperadorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void ObtieneDetallesCorteOperadorCompletedEventHandler(object sender, ObtieneDetallesCorteOperadorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtieneDetallesCorteOperadorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtieneDetallesCorteOperadorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void EnviaSMSCompletedEventHandler(object sender, EnviaSMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviaSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviaSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void CentralMovilConsultarUltimaOperacionCompletedEventHandler(object sender, CentralMovilConsultarUltimaOperacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CentralMovilConsultarUltimaOperacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CentralMovilConsultarUltimaOperacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public operacion Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((operacion)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void CrearEmpleadoClubEscalaCompletedEventHandler(object sender, CrearEmpleadoClubEscalaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrearEmpleadoClubEscalaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CrearEmpleadoClubEscalaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void CentralMovilConsultarCortesCompletedEventHandler(object sender, CentralMovilConsultarCortesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CentralMovilConsultarCortesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CentralMovilConsultarCortesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void CentralMovilObtieneColectivaCompletedEventHandler(object sender, CentralMovilObtieneColectivaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CentralMovilObtieneColectivaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CentralMovilObtieneColectivaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public colectiva Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((colectiva)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void CentralMovilCortarCompletedEventHandler(object sender, CentralMovilCortarCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CentralMovilCortarCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CentralMovilCortarCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void CrearUsuarioShopAndWinCompletedEventHandler(object sender, CrearUsuarioShopAndWinCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrearUsuarioShopAndWinCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CrearUsuarioShopAndWinCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void CrearCuentasaEmpleadoClubEscalaCompletedEventHandler(object sender, CrearCuentasaEmpleadoClubEscalaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrearCuentasaEmpleadoClubEscalaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CrearCuentasaEmpleadoClubEscalaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    public delegate void CentralMovilConsultarOperacionesCompletedEventHandler(object sender, CentralMovilConsultarOperacionesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18213")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CentralMovilConsultarOperacionesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CentralMovilConsultarOperacionesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591