using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Dnu.AutorizadorParabilia_NCliente.Entidades
{
    public class EntradaWSEvertecAlta
    {
        public string Numero_Solicitud { get; set; }
        public string Tipo_Registro { get; set; }
        public string Numero_Cedula { get; set; }
        public string Personeria { get; set; }
        public string Nombre_Cliente { get; set; }
        public string Segundo_Nombre { get; set; }
        public string Primer_Apellido { get; set; }
        public string Segundo_Apellido { get; set; }
        public string Apellido_Casada { get; set; }
        public string Estado_Civil { get; set; }
        public string Fecha_Nacimiento { get; set; }
        public string Monto_ingreso { get; set; }
        public string Moneda_ingreso { get; set; }
        public string Codigo_Profesion { get; set; }
        public string Nacionalidad { get; set; }
        public string Sexo { get; set; }
        public string Provincia_Tarjetahabiente { get; set; }
        public string Canton_Tarjetahabiente { get; set; }
        public string Distrito_Tarjetahabiente { get; set; }
        public string Direccion_Tarjetahabiente { get; set; }
        public string Telefono_habitacion { get; set; }
        public string Numero_fax { get; set; }
        public string Telefono_celular { get; set; }
        public string Radio_localizador { get; set; }
        public string Correo_electronico { get; set; }
        public string Codigo_Postal { get; set; }
        public string Apartado_Postal { get; set; }
        public string Nombre_Patrono { get; set; }
        public string Telefono_Oficina { get; set; }
        public string Fax_Trabajo { get; set; }
        public string Provincia_trabajo { get; set; }
        public string Canton_trabajo { get; set; }
        public string Distrito_trabajo { get; set; }
        public string Direccion_Patrono { get; set; }
        public string Zona_Postal_Patrono { get; set; }
        public string Apartado_Postal_Patrono { get; set; }
        public string Codigo_parentesco_pariente { get; set; }
        public string Limite_Credito { get; set; }
        public string Moneda_Emisor { get; set; }
        public string Sucursal_Retiro_Tarjeta { get; set; }
        public string Ciclo_Corte { get; set; }
        public string Emisor { get; set; }
        public string Nombre_Embozar { get; set; }
        public string Cuenta_CMB_CDB { get; set; }
        public string Tipo_Garantia { get; set; }
        public string Descuento_membresia { get; set; }
        public string Tipo_Cliente { get; set; }
        public string ICE { get; set; }
        public string Tarjeta_Telefonica { get; set; }
        public string Indicador_Plan { get; set; }
        public string Numero_Empresa { get; set; }
        public string Cedula_Conyuge { get; set; }
        public string Nombre_Conyuge { get; set; }
        public string Cuenta_Valor { get; set; }
        public string Tipo_Poliza { get; set; }
        public string Codigo_Vendedor { get; set; }
        public string Direccion_EstadoCuenta { get; set; }
        public string Ciudad_Envio { get; set; }
        public string Codigo_Postal_envio { get; set; }
        public string Apartado_Postal_envio { get; set; }
        public string Nombre_Pariente { get; set; }
        public string Primer_Apellido_Pariente { get; set; }
        public string Segundo_Apellido_Pariente { get; set; }
        public string Telefono_Pariente { get; set; }
        public string Direccion_Pariente { get; set; }
        public string Ciudad_Pariente { get; set; }
        public string Codigo_Postal_Pariente { get; set; }
        public string Apartado_Postal_Pariente { get; set; }
        public string Programa_Premiacion { get; set; }
        public string Codigo_superfranquicia { get; set; }
        public string Tipo_Tarjeta { get; set; }
        public string Codigo_Diseno { get; set; }
        public string Correo_electronico_EstadoCTA { get; set; }
        public string Filler_01 { get; set; }
        public string Filler_02 { get; set; }
        public string Filler_03 { get; set; }
        public string Couries { get; set; }
        public string Filler_05 { get; set; }
        public string Filler_06 { get; set; }
        public string Tipo_identificacion { get; set; }
        public string Codigo_emision_Identidad { get; set; }
        public string Numero_NIT { get; set; }
        public string Lugar_emision_NIT { get; set; }
        public string Categoria_Cliente { get; set; }
        public string Campania { get; set; }
        public string Localidad_cuenta { get; set; }
        public string Numero_cliente { get; set; }
        public string Indicador_cuota_fija { get; set; }
        public string Cuota_Fija { get; set; }
        public string Codigo_Postal_Est_Cuenta { get; set; }
        public string Codigo_Postal_Apartado { get; set; }
        public string Region { get; set; }
        public string Zona { get; set; }
        public string Sector { get; set; }
        public string Plan_Poliza { get; set; }
        public string Numero_Poliza { get; set; }
        public string Direccion_3_TH { get; set; }
        public string Direccion_3_EC { get; set; }
        public string Shipping_address { get; set; }
        public string Plan_base_compras { get; set; }
        public string Plan_base_adelantos { get; set; }
        public string Razon_creacion_cta { get; set; }
        public string Aplica_Recargo_cuota_vencida { get; set; }
        public string Cobra_comision_adelanto { get; set; }
        public string Cobra_comision_cuasi_cash { get; set; }
        public string Aplica_cargo_sobregiro { get; set; }
        public string Cobra_interes { get; set; }
        public string Aplica_cargo_cheque_devuelto { get; set; }
        public string Permite_rebajo_pago_automatico { get; set; }
        public string Rebajo_pago_fijo { get; set; }
        public string Monto_pago_fijo { get; set; }
        public string Rebajo_pago_contado { get; set; }
        public string Numero_cuenta { get; set; }
        public string Seguro_social { get; set; }
        public string Calificativo { get; set; }
        public string Telefono_conyuge { get; set; }
        public string Telefono_trabajo_conyuge { get; set; }
        public string Lugar_trabajo_conyuge { get; set; }
        public string Cobra_impuestos_FECI { get; set; }
        public string Fecha_Cobro_Membresia { get; set; }
        public string Filler_07 { get; set; }
        public string Filler_08 { get; set; }
        public string Filler_09 { get; set; }
        public string Filler_10 { get; set; }
        public string Filler_11 { get; set; }
        public string Codigo_Autonomia { get; set; }
        public string Codigo_usuario_autonomia { get; set; }
        public string Empresa_Cobro { get; set; }
        public string Registro_Tributario_Nacional { get; set; }
        public string Numero_cuenta_Siscard { get; set; }
        public string Poliza_2 { get; set; }
        public string Numero_Poliza_2 { get; set; }
        public string Tipo_Vivienda { get; set; }
        public string Area_Actividad_economica { get; set; }
        public string Actividad_Economica { get; set; }
        public string Usuario { get; set; }
        public string Forma_Envio_Estados_Cuenta { get; set; }
        public string Numero_Documento_Garantia { get; set; }
        public string Valor_En_Garantia { get; set; }
    }
}
