//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace ImportarEmpleados.WsTransaction {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TransactionProcessPortBinding", Namespace="http://ws.wscomponent.com/")]
    public partial class TransactionProcess : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SendTransactionOperationCompleted;
        
        private System.Threading.SendOrPostCallback SellOperationCompleted;
        
        private System.Threading.SendOrPostCallback Sell2OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TransactionProcess() {
            this.Url = global::ImportarEmpleados.Properties.Settings.Default.ImportarEmpleados_WsTransaction_TransactionProcessService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SendTransactionCompletedEventHandler SendTransactionCompleted;
        
        /// <remarks/>
        public event SellCompletedEventHandler SellCompleted;
        
        /// <remarks/>
        public event Sell2CompletedEventHandler Sell2Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.wscomponent.com/", ResponseNamespace="http://ws.wscomponent.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public respuesta SendTransaction(
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _pIsReversal, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _pTransactionTyper, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _pVersionNumber, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _pFieldInError, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _pOriginalEntity, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _pDestinationEntity, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _pTransactionTypeCode, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _pAccountTypeCode1, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _pAccountTypeCode2, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _pCurrencyCode, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _pDecimalPlace, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _pTransactionAmount, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _pTPVDate, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _pTPVTime, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _pAccessCard, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _pVerficationCard, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _pPOSEnviroment, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _pSecurityCard, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _pMerchantType, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _pAcquiringInstitutionIdentification, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _pTrack2, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _pRetrievalReferenceNumber, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _pCardAcceptorTerminal, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _pCardAcceptorIdentification, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _pAditionalDataPrivate, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _pPINData, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _pAdditionalAmounts, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _pOriginalTransactionTypeCode, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _pOriginalTraceAuditNumber, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _pOriginalDateTime, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _pOriginalAcquiringInstitutionIdentification, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _pTransportData, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _pAccessAcountType, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _pAccessAcountIdentifier, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _pServiceReferenceNumber, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _pInstitucionCode, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _pPayee, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _pAdditionalSKUS) {
            object[] results = this.Invoke("SendTransaction", new object[] {
                        _pIsReversal,
                        _pTransactionTyper,
                        _pVersionNumber,
                        _pFieldInError,
                        _pOriginalEntity,
                        _pDestinationEntity,
                        _pTransactionTypeCode,
                        _pAccountTypeCode1,
                        _pAccountTypeCode2,
                        _pCurrencyCode,
                        _pDecimalPlace,
                        _pTransactionAmount,
                        _pTPVDate,
                        _pTPVTime,
                        _pAccessCard,
                        _pVerficationCard,
                        _pPOSEnviroment,
                        _pSecurityCard,
                        _pMerchantType,
                        _pAcquiringInstitutionIdentification,
                        _pTrack2,
                        _pRetrievalReferenceNumber,
                        _pCardAcceptorTerminal,
                        _pCardAcceptorIdentification,
                        _pAditionalDataPrivate,
                        _pPINData,
                        _pAdditionalAmounts,
                        _pOriginalTransactionTypeCode,
                        _pOriginalTraceAuditNumber,
                        _pOriginalDateTime,
                        _pOriginalAcquiringInstitutionIdentification,
                        _pTransportData,
                        _pAccessAcountType,
                        _pAccessAcountIdentifier,
                        _pServiceReferenceNumber,
                        _pInstitucionCode,
                        _pPayee,
                        _pAdditionalSKUS});
            return ((respuesta)(results[0]));
        }
        
        /// <remarks/>
        public void SendTransactionAsync(
                    string _pIsReversal, 
                    string _pTransactionTyper, 
                    string _pVersionNumber, 
                    string _pFieldInError, 
                    string _pOriginalEntity, 
                    string _pDestinationEntity, 
                    string _pTransactionTypeCode, 
                    string _pAccountTypeCode1, 
                    string _pAccountTypeCode2, 
                    string _pCurrencyCode, 
                    string _pDecimalPlace, 
                    string _pTransactionAmount, 
                    string _pTPVDate, 
                    string _pTPVTime, 
                    string _pAccessCard, 
                    string _pVerficationCard, 
                    string _pPOSEnviroment, 
                    string _pSecurityCard, 
                    string _pMerchantType, 
                    string _pAcquiringInstitutionIdentification, 
                    string _pTrack2, 
                    string _pRetrievalReferenceNumber, 
                    string _pCardAcceptorTerminal, 
                    string _pCardAcceptorIdentification, 
                    string _pAditionalDataPrivate, 
                    string _pPINData, 
                    string _pAdditionalAmounts, 
                    string _pOriginalTransactionTypeCode, 
                    string _pOriginalTraceAuditNumber, 
                    string _pOriginalDateTime, 
                    string _pOriginalAcquiringInstitutionIdentification, 
                    string _pTransportData, 
                    string _pAccessAcountType, 
                    string _pAccessAcountIdentifier, 
                    string _pServiceReferenceNumber, 
                    string _pInstitucionCode, 
                    string _pPayee, 
                    string _pAdditionalSKUS) {
            this.SendTransactionAsync(_pIsReversal, _pTransactionTyper, _pVersionNumber, _pFieldInError, _pOriginalEntity, _pDestinationEntity, _pTransactionTypeCode, _pAccountTypeCode1, _pAccountTypeCode2, _pCurrencyCode, _pDecimalPlace, _pTransactionAmount, _pTPVDate, _pTPVTime, _pAccessCard, _pVerficationCard, _pPOSEnviroment, _pSecurityCard, _pMerchantType, _pAcquiringInstitutionIdentification, _pTrack2, _pRetrievalReferenceNumber, _pCardAcceptorTerminal, _pCardAcceptorIdentification, _pAditionalDataPrivate, _pPINData, _pAdditionalAmounts, _pOriginalTransactionTypeCode, _pOriginalTraceAuditNumber, _pOriginalDateTime, _pOriginalAcquiringInstitutionIdentification, _pTransportData, _pAccessAcountType, _pAccessAcountIdentifier, _pServiceReferenceNumber, _pInstitucionCode, _pPayee, _pAdditionalSKUS, null);
        }
        
        /// <remarks/>
        public void SendTransactionAsync(
                    string _pIsReversal, 
                    string _pTransactionTyper, 
                    string _pVersionNumber, 
                    string _pFieldInError, 
                    string _pOriginalEntity, 
                    string _pDestinationEntity, 
                    string _pTransactionTypeCode, 
                    string _pAccountTypeCode1, 
                    string _pAccountTypeCode2, 
                    string _pCurrencyCode, 
                    string _pDecimalPlace, 
                    string _pTransactionAmount, 
                    string _pTPVDate, 
                    string _pTPVTime, 
                    string _pAccessCard, 
                    string _pVerficationCard, 
                    string _pPOSEnviroment, 
                    string _pSecurityCard, 
                    string _pMerchantType, 
                    string _pAcquiringInstitutionIdentification, 
                    string _pTrack2, 
                    string _pRetrievalReferenceNumber, 
                    string _pCardAcceptorTerminal, 
                    string _pCardAcceptorIdentification, 
                    string _pAditionalDataPrivate, 
                    string _pPINData, 
                    string _pAdditionalAmounts, 
                    string _pOriginalTransactionTypeCode, 
                    string _pOriginalTraceAuditNumber, 
                    string _pOriginalDateTime, 
                    string _pOriginalAcquiringInstitutionIdentification, 
                    string _pTransportData, 
                    string _pAccessAcountType, 
                    string _pAccessAcountIdentifier, 
                    string _pServiceReferenceNumber, 
                    string _pInstitucionCode, 
                    string _pPayee, 
                    string _pAdditionalSKUS, 
                    object userState) {
            if ((this.SendTransactionOperationCompleted == null)) {
                this.SendTransactionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendTransactionOperationCompleted);
            }
            this.InvokeAsync("SendTransaction", new object[] {
                        _pIsReversal,
                        _pTransactionTyper,
                        _pVersionNumber,
                        _pFieldInError,
                        _pOriginalEntity,
                        _pDestinationEntity,
                        _pTransactionTypeCode,
                        _pAccountTypeCode1,
                        _pAccountTypeCode2,
                        _pCurrencyCode,
                        _pDecimalPlace,
                        _pTransactionAmount,
                        _pTPVDate,
                        _pTPVTime,
                        _pAccessCard,
                        _pVerficationCard,
                        _pPOSEnviroment,
                        _pSecurityCard,
                        _pMerchantType,
                        _pAcquiringInstitutionIdentification,
                        _pTrack2,
                        _pRetrievalReferenceNumber,
                        _pCardAcceptorTerminal,
                        _pCardAcceptorIdentification,
                        _pAditionalDataPrivate,
                        _pPINData,
                        _pAdditionalAmounts,
                        _pOriginalTransactionTypeCode,
                        _pOriginalTraceAuditNumber,
                        _pOriginalDateTime,
                        _pOriginalAcquiringInstitutionIdentification,
                        _pTransportData,
                        _pAccessAcountType,
                        _pAccessAcountIdentifier,
                        _pServiceReferenceNumber,
                        _pInstitucionCode,
                        _pPayee,
                        _pAdditionalSKUS}, this.SendTransactionOperationCompleted, userState);
        }
        
        private void OnSendTransactionOperationCompleted(object arg) {
            if ((this.SendTransactionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendTransactionCompleted(this, new SendTransactionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.wscomponent.com/", ResponseNamespace="http://ws.wscomponent.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public trxRespuesta Sell([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Password, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string MedioPago, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Sucursal, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Afiliacion, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Terminal, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] float Importe, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Referencia, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Ticket, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Compania) {
            object[] results = this.Invoke("Sell", new object[] {
                        Usuario,
                        Password,
                        MedioPago,
                        Sucursal,
                        Afiliacion,
                        Terminal,
                        Importe,
                        Referencia,
                        Ticket,
                        Compania});
            return ((trxRespuesta)(results[0]));
        }
        
        /// <remarks/>
        public void SellAsync(string Usuario, string Password, string MedioPago, string Sucursal, string Afiliacion, string Terminal, float Importe, string Referencia, string Ticket, string Compania) {
            this.SellAsync(Usuario, Password, MedioPago, Sucursal, Afiliacion, Terminal, Importe, Referencia, Ticket, Compania, null);
        }
        
        /// <remarks/>
        public void SellAsync(string Usuario, string Password, string MedioPago, string Sucursal, string Afiliacion, string Terminal, float Importe, string Referencia, string Ticket, string Compania, object userState) {
            if ((this.SellOperationCompleted == null)) {
                this.SellOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSellOperationCompleted);
            }
            this.InvokeAsync("Sell", new object[] {
                        Usuario,
                        Password,
                        MedioPago,
                        Sucursal,
                        Afiliacion,
                        Terminal,
                        Importe,
                        Referencia,
                        Ticket,
                        Compania}, this.SellOperationCompleted, userState);
        }
        
        private void OnSellOperationCompleted(object arg) {
            if ((this.SellCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SellCompleted(this, new SellCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.wscomponent.com/", ResponseNamespace="http://ws.wscomponent.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public trxRespuesta Sell2([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Password, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string MedioPago, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Sucursal, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Afiliacion, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Terminal, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] float Importe, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Referencia, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Ticket, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Compania, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Cliente) {
            object[] results = this.Invoke("Sell2", new object[] {
                        Usuario,
                        Password,
                        MedioPago,
                        Sucursal,
                        Afiliacion,
                        Terminal,
                        Importe,
                        Referencia,
                        Ticket,
                        Compania,
                        Cliente});
            return ((trxRespuesta)(results[0]));
        }
        
        /// <remarks/>
        public void Sell2Async(string Usuario, string Password, string MedioPago, string Sucursal, string Afiliacion, string Terminal, float Importe, string Referencia, string Ticket, string Compania, string Cliente) {
            this.Sell2Async(Usuario, Password, MedioPago, Sucursal, Afiliacion, Terminal, Importe, Referencia, Ticket, Compania, Cliente, null);
        }
        
        /// <remarks/>
        public void Sell2Async(string Usuario, string Password, string MedioPago, string Sucursal, string Afiliacion, string Terminal, float Importe, string Referencia, string Ticket, string Compania, string Cliente, object userState) {
            if ((this.Sell2OperationCompleted == null)) {
                this.Sell2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnSell2OperationCompleted);
            }
            this.InvokeAsync("Sell2", new object[] {
                        Usuario,
                        Password,
                        MedioPago,
                        Sucursal,
                        Afiliacion,
                        Terminal,
                        Importe,
                        Referencia,
                        Ticket,
                        Compania,
                        Cliente}, this.Sell2OperationCompleted, userState);
        }
        
        private void OnSell2OperationCompleted(object arg) {
            if ((this.Sell2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Sell2Completed(this, new Sell2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.wscomponent.com/")]
    public partial class respuesta {
        
        private int tipoField;
        
        private string _rAdditionalAmountsField;
        
        private string _rAuthorizationResponseField;
        
        private string _rCardIssuerTelephoneNumberField;
        
        private string _rDescResponseCodeField;
        
        private string _rMessageAcceptorPrintField;
        
        private string _rMessageAcceptorScreenField;
        
        private string _rMessageClientScreenField;
        
        private string _rMessageClientTicketField;
        
        private bool _rResponseArrivedField;
        
        private string _rResponseCodeField;
        
        private string _rResultField;
        
        private bool _rTimeOutField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _rAdditionalAmounts {
            get {
                return this._rAdditionalAmountsField;
            }
            set {
                this._rAdditionalAmountsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _rAuthorizationResponse {
            get {
                return this._rAuthorizationResponseField;
            }
            set {
                this._rAuthorizationResponseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _rCardIssuerTelephoneNumber {
            get {
                return this._rCardIssuerTelephoneNumberField;
            }
            set {
                this._rCardIssuerTelephoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _rDescResponseCode {
            get {
                return this._rDescResponseCodeField;
            }
            set {
                this._rDescResponseCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _rMessageAcceptorPrint {
            get {
                return this._rMessageAcceptorPrintField;
            }
            set {
                this._rMessageAcceptorPrintField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _rMessageAcceptorScreen {
            get {
                return this._rMessageAcceptorScreenField;
            }
            set {
                this._rMessageAcceptorScreenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _rMessageClientScreen {
            get {
                return this._rMessageClientScreenField;
            }
            set {
                this._rMessageClientScreenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _rMessageClientTicket {
            get {
                return this._rMessageClientTicketField;
            }
            set {
                this._rMessageClientTicketField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool _rResponseArrived {
            get {
                return this._rResponseArrivedField;
            }
            set {
                this._rResponseArrivedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _rResponseCode {
            get {
                return this._rResponseCodeField;
            }
            set {
                this._rResponseCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string _rResult {
            get {
                return this._rResultField;
            }
            set {
                this._rResultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool _rTimeOut {
            get {
                return this._rTimeOutField;
            }
            set {
                this._rTimeOutField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.wscomponent.com/")]
    public partial class trxRespuesta {
        
        private string autorizacionField;
        
        private int codigoRespuestaField;
        
        private string descripcionField;
        
        private float importeField;
        
        private string leyendaField;
        
        private string referenciaField;
        
        private string terminalField;
        
        private string ticketField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string autorizacion {
            get {
                return this.autorizacionField;
            }
            set {
                this.autorizacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigoRespuesta {
            get {
                return this.codigoRespuestaField;
            }
            set {
                this.codigoRespuestaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float importe {
            get {
                return this.importeField;
            }
            set {
                this.importeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string leyenda {
            get {
                return this.leyendaField;
            }
            set {
                this.leyendaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string referencia {
            get {
                return this.referenciaField;
            }
            set {
                this.referenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string terminal {
            get {
                return this.terminalField;
            }
            set {
                this.terminalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ticket {
            get {
                return this.ticketField;
            }
            set {
                this.ticketField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SendTransactionCompletedEventHandler(object sender, SendTransactionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendTransactionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendTransactionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public respuesta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((respuesta)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SellCompletedEventHandler(object sender, SellCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SellCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SellCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public trxRespuesta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((trxRespuesta)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void Sell2CompletedEventHandler(object sender, Sell2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Sell2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Sell2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public trxRespuesta Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((trxRespuesta)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591