//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNU_Embozador.WS_CLAI_Embozamiento {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://embozamiento.wsbeans.iseries/", ConfigurationName="WS_CLAI_Embozamiento.EmbozamientoServices")]
    public interface EmbozamientoServices {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://embozamiento.wsbeans.iseries/EmbozamientoServices/pgmactRequest", ReplyAction="http://embozamiento.wsbeans.iseries/EmbozamientoServices/pgmactResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        DNU_Embozador.WS_CLAI_Embozamiento.pgmactResponse pgmact(DNU_Embozador.WS_CLAI_Embozamiento.pgmactRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://embozamiento.wsbeans.iseries/EmbozamientoServices/pgmactRequest", ReplyAction="http://embozamiento.wsbeans.iseries/EmbozamientoServices/pgmactResponse")]
        System.Threading.Tasks.Task<DNU_Embozador.WS_CLAI_Embozamiento.pgmactResponse> pgmactAsync(DNU_Embozador.WS_CLAI_Embozamiento.pgmactRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://embozamiento.wsbeans.iseries/")]
    public partial class pgmactInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cODRESPUESTAField;
        
        private string cRIPTOPINField;
        
        private string cVVField;
        
        private string cVV2Field;
        
        private string dESCRESPUESTAField;
        
        private string fECEXPIRACIONField;
        
        private string fORPINBLOCKField;
        
        private string iDSOLICITUDField;
        
        private string pVVField;
        
        private string tARJETAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CODRESPUESTA {
            get {
                return this.cODRESPUESTAField;
            }
            set {
                this.cODRESPUESTAField = value;
                this.RaisePropertyChanged("CODRESPUESTA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CRIPTOPIN {
            get {
                return this.cRIPTOPINField;
            }
            set {
                this.cRIPTOPINField = value;
                this.RaisePropertyChanged("CRIPTOPIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string CVV {
            get {
                return this.cVVField;
            }
            set {
                this.cVVField = value;
                this.RaisePropertyChanged("CVV");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string CVV2 {
            get {
                return this.cVV2Field;
            }
            set {
                this.cVV2Field = value;
                this.RaisePropertyChanged("CVV2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string DESCRESPUESTA {
            get {
                return this.dESCRESPUESTAField;
            }
            set {
                this.dESCRESPUESTAField = value;
                this.RaisePropertyChanged("DESCRESPUESTA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string FECEXPIRACION {
            get {
                return this.fECEXPIRACIONField;
            }
            set {
                this.fECEXPIRACIONField = value;
                this.RaisePropertyChanged("FECEXPIRACION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string FORPINBLOCK {
            get {
                return this.fORPINBLOCKField;
            }
            set {
                this.fORPINBLOCKField = value;
                this.RaisePropertyChanged("FORPINBLOCK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string IDSOLICITUD {
            get {
                return this.iDSOLICITUDField;
            }
            set {
                this.iDSOLICITUDField = value;
                this.RaisePropertyChanged("IDSOLICITUD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string PVV {
            get {
                return this.pVVField;
            }
            set {
                this.pVVField = value;
                this.RaisePropertyChanged("PVV");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string TARJETA {
            get {
                return this.tARJETAField;
            }
            set {
                this.tARJETAField = value;
                this.RaisePropertyChanged("TARJETA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://embozamiento.wsbeans.iseries/")]
    public partial class pgmactResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cODRESPUESTAField;
        
        private string cRIPTOPINField;
        
        private string cVVField;
        
        private string cVV2Field;
        
        private string dESCRESPUESTAField;
        
        private string fECEXPIRACIONField;
        
        private string fORPINBLOCKField;
        
        private string iDSOLICITUDField;
        
        private string pVVField;
        
        private string tARJETAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CODRESPUESTA {
            get {
                return this.cODRESPUESTAField;
            }
            set {
                this.cODRESPUESTAField = value;
                this.RaisePropertyChanged("CODRESPUESTA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string CRIPTOPIN {
            get {
                return this.cRIPTOPINField;
            }
            set {
                this.cRIPTOPINField = value;
                this.RaisePropertyChanged("CRIPTOPIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string CVV {
            get {
                return this.cVVField;
            }
            set {
                this.cVVField = value;
                this.RaisePropertyChanged("CVV");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string CVV2 {
            get {
                return this.cVV2Field;
            }
            set {
                this.cVV2Field = value;
                this.RaisePropertyChanged("CVV2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string DESCRESPUESTA {
            get {
                return this.dESCRESPUESTAField;
            }
            set {
                this.dESCRESPUESTAField = value;
                this.RaisePropertyChanged("DESCRESPUESTA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string FECEXPIRACION {
            get {
                return this.fECEXPIRACIONField;
            }
            set {
                this.fECEXPIRACIONField = value;
                this.RaisePropertyChanged("FECEXPIRACION");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string FORPINBLOCK {
            get {
                return this.fORPINBLOCKField;
            }
            set {
                this.fORPINBLOCKField = value;
                this.RaisePropertyChanged("FORPINBLOCK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string IDSOLICITUD {
            get {
                return this.iDSOLICITUDField;
            }
            set {
                this.iDSOLICITUDField = value;
                this.RaisePropertyChanged("IDSOLICITUD");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string PVV {
            get {
                return this.pVVField;
            }
            set {
                this.pVVField = value;
                this.RaisePropertyChanged("PVV");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string TARJETA {
            get {
                return this.tARJETAField;
            }
            set {
                this.tARJETAField = value;
                this.RaisePropertyChanged("TARJETA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pgmact", WrapperNamespace="http://embozamiento.wsbeans.iseries/", IsWrapped=true)]
    public partial class pgmactRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://embozamiento.wsbeans.iseries/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DNU_Embozador.WS_CLAI_Embozamiento.pgmactInput arg0;
        
        public pgmactRequest() {
        }
        
        public pgmactRequest(DNU_Embozador.WS_CLAI_Embozamiento.pgmactInput arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pgmactResponse", WrapperNamespace="http://embozamiento.wsbeans.iseries/", IsWrapped=true)]
    public partial class pgmactResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://embozamiento.wsbeans.iseries/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DNU_Embozador.WS_CLAI_Embozamiento.pgmactResult @return;
        
        public pgmactResponse() {
        }
        
        public pgmactResponse(DNU_Embozador.WS_CLAI_Embozamiento.pgmactResult @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmbozamientoServicesChannel : DNU_Embozador.WS_CLAI_Embozamiento.EmbozamientoServices, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmbozamientoServicesClient : System.ServiceModel.ClientBase<DNU_Embozador.WS_CLAI_Embozamiento.EmbozamientoServices>, DNU_Embozador.WS_CLAI_Embozamiento.EmbozamientoServices {
        
        public EmbozamientoServicesClient() {
        }
        
        public EmbozamientoServicesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmbozamientoServicesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmbozamientoServicesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmbozamientoServicesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DNU_Embozador.WS_CLAI_Embozamiento.pgmactResponse DNU_Embozador.WS_CLAI_Embozamiento.EmbozamientoServices.pgmact(DNU_Embozador.WS_CLAI_Embozamiento.pgmactRequest request) {
            return base.Channel.pgmact(request);
        }
        
        public DNU_Embozador.WS_CLAI_Embozamiento.pgmactResult pgmact(DNU_Embozador.WS_CLAI_Embozamiento.pgmactInput arg0) {
            DNU_Embozador.WS_CLAI_Embozamiento.pgmactRequest inValue = new DNU_Embozador.WS_CLAI_Embozamiento.pgmactRequest();
            inValue.arg0 = arg0;
            DNU_Embozador.WS_CLAI_Embozamiento.pgmactResponse retVal = ((DNU_Embozador.WS_CLAI_Embozamiento.EmbozamientoServices)(this)).pgmact(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DNU_Embozador.WS_CLAI_Embozamiento.pgmactResponse> DNU_Embozador.WS_CLAI_Embozamiento.EmbozamientoServices.pgmactAsync(DNU_Embozador.WS_CLAI_Embozamiento.pgmactRequest request) {
            return base.Channel.pgmactAsync(request);
        }
        
        public System.Threading.Tasks.Task<DNU_Embozador.WS_CLAI_Embozamiento.pgmactResponse> pgmactAsync(DNU_Embozador.WS_CLAI_Embozamiento.pgmactInput arg0) {
            DNU_Embozador.WS_CLAI_Embozamiento.pgmactRequest inValue = new DNU_Embozador.WS_CLAI_Embozamiento.pgmactRequest();
            inValue.arg0 = arg0;
            return ((DNU_Embozador.WS_CLAI_Embozamiento.EmbozamientoServices)(this)).pgmactAsync(inValue);
        }
    }
}
