//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace ImportarEmpleados.ws_CEscala {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS_AdministracionPortBinding", Namespace="http://Admin/")]
    public partial class WS_Administracion : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ActualizaPasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback GeneraCorteOperadorOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtieneDetallesCorteOperadorOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviaSMSOperationCompleted;
        
        private System.Threading.SendOrPostCallback CrearEmpleadoClubEscalaOperationCompleted;
        
        private System.Threading.SendOrPostCallback CrearCuentasaEmpleadoClubEscalaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS_Administracion() {
            this.Url = global::ImportarEmpleados.Properties.Settings.Default.ImportarEmpleados_ws_CEscala_WS_Administracion;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ActualizaPasswordCompletedEventHandler ActualizaPasswordCompleted;
        
        /// <remarks/>
        public event GeneraCorteOperadorCompletedEventHandler GeneraCorteOperadorCompleted;
        
        /// <remarks/>
        public event ObtieneDetallesCorteOperadorCompletedEventHandler ObtieneDetallesCorteOperadorCompleted;
        
        /// <remarks/>
        public event EnviaSMSCompletedEventHandler EnviaSMSCompleted;
        
        /// <remarks/>
        public event CrearEmpleadoClubEscalaCompletedEventHandler CrearEmpleadoClubEscalaCompleted;
        
        /// <remarks/>
        public event CrearCuentasaEmpleadoClubEscalaCompletedEventHandler CrearCuentasaEmpleadoClubEscalaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Admin/", ResponseNamespace="http://Admin/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ActualizaPassword([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string password, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ClaveEvento, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ClaveTipoMA, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ClaveMedioAcceso, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string NIPNuevo, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string NIPAnterior) {
            object[] results = this.Invoke("ActualizaPassword", new object[] {
                        usuario,
                        password,
                        ClaveEvento,
                        ClaveTipoMA,
                        ClaveMedioAcceso,
                        NIPNuevo,
                        NIPAnterior});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void ActualizaPasswordAsync(string usuario, string password, string ClaveEvento, string ClaveTipoMA, string ClaveMedioAcceso, string NIPNuevo, string NIPAnterior) {
            this.ActualizaPasswordAsync(usuario, password, ClaveEvento, ClaveTipoMA, ClaveMedioAcceso, NIPNuevo, NIPAnterior, null);
        }
        
        /// <remarks/>
        public void ActualizaPasswordAsync(string usuario, string password, string ClaveEvento, string ClaveTipoMA, string ClaveMedioAcceso, string NIPNuevo, string NIPAnterior, object userState) {
            if ((this.ActualizaPasswordOperationCompleted == null)) {
                this.ActualizaPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnActualizaPasswordOperationCompleted);
            }
            this.InvokeAsync("ActualizaPassword", new object[] {
                        usuario,
                        password,
                        ClaveEvento,
                        ClaveTipoMA,
                        ClaveMedioAcceso,
                        NIPNuevo,
                        NIPAnterior}, this.ActualizaPasswordOperationCompleted, userState);
        }
        
        private void OnActualizaPasswordOperationCompleted(object arg) {
            if ((this.ActualizaPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ActualizaPasswordCompleted(this, new ActualizaPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Admin/", ResponseNamespace="http://Admin/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int GeneraCorteOperador([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string password, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ClaveEvento, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ClaveOperador) {
            object[] results = this.Invoke("GeneraCorteOperador", new object[] {
                        usuario,
                        password,
                        ClaveEvento,
                        ClaveOperador});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GeneraCorteOperadorAsync(string usuario, string password, string ClaveEvento, string ClaveOperador) {
            this.GeneraCorteOperadorAsync(usuario, password, ClaveEvento, ClaveOperador, null);
        }
        
        /// <remarks/>
        public void GeneraCorteOperadorAsync(string usuario, string password, string ClaveEvento, string ClaveOperador, object userState) {
            if ((this.GeneraCorteOperadorOperationCompleted == null)) {
                this.GeneraCorteOperadorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGeneraCorteOperadorOperationCompleted);
            }
            this.InvokeAsync("GeneraCorteOperador", new object[] {
                        usuario,
                        password,
                        ClaveEvento,
                        ClaveOperador}, this.GeneraCorteOperadorOperationCompleted, userState);
        }
        
        private void OnGeneraCorteOperadorOperationCompleted(object arg) {
            if ((this.GeneraCorteOperadorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GeneraCorteOperadorCompleted(this, new GeneraCorteOperadorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Admin/", ResponseNamespace="http://Admin/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ObtieneDetallesCorteOperador([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string password, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ClaveEvento, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ClaveOperador, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int TipoReporte) {
            object[] results = this.Invoke("ObtieneDetallesCorteOperador", new object[] {
                        usuario,
                        password,
                        ClaveEvento,
                        ClaveOperador,
                        TipoReporte});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ObtieneDetallesCorteOperadorAsync(string usuario, string password, string ClaveEvento, string ClaveOperador, int TipoReporte) {
            this.ObtieneDetallesCorteOperadorAsync(usuario, password, ClaveEvento, ClaveOperador, TipoReporte, null);
        }
        
        /// <remarks/>
        public void ObtieneDetallesCorteOperadorAsync(string usuario, string password, string ClaveEvento, string ClaveOperador, int TipoReporte, object userState) {
            if ((this.ObtieneDetallesCorteOperadorOperationCompleted == null)) {
                this.ObtieneDetallesCorteOperadorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtieneDetallesCorteOperadorOperationCompleted);
            }
            this.InvokeAsync("ObtieneDetallesCorteOperador", new object[] {
                        usuario,
                        password,
                        ClaveEvento,
                        ClaveOperador,
                        TipoReporte}, this.ObtieneDetallesCorteOperadorOperationCompleted, userState);
        }
        
        private void OnObtieneDetallesCorteOperadorOperationCompleted(object arg) {
            if ((this.ObtieneDetallesCorteOperadorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtieneDetallesCorteOperadorCompleted(this, new ObtieneDetallesCorteOperadorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Admin/", ResponseNamespace="http://Admin/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int EnviaSMS([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string password, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ClaveEvento, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Telefono, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Mensaje) {
            object[] results = this.Invoke("EnviaSMS", new object[] {
                        usuario,
                        password,
                        ClaveEvento,
                        Telefono,
                        Mensaje});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void EnviaSMSAsync(string usuario, string password, string ClaveEvento, string Telefono, string Mensaje) {
            this.EnviaSMSAsync(usuario, password, ClaveEvento, Telefono, Mensaje, null);
        }
        
        /// <remarks/>
        public void EnviaSMSAsync(string usuario, string password, string ClaveEvento, string Telefono, string Mensaje, object userState) {
            if ((this.EnviaSMSOperationCompleted == null)) {
                this.EnviaSMSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviaSMSOperationCompleted);
            }
            this.InvokeAsync("EnviaSMS", new object[] {
                        usuario,
                        password,
                        ClaveEvento,
                        Telefono,
                        Mensaje}, this.EnviaSMSOperationCompleted, userState);
        }
        
        private void OnEnviaSMSOperationCompleted(object arg) {
            if ((this.EnviaSMSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviaSMSCompleted(this, new EnviaSMSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Admin/", ResponseNamespace="http://Admin/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int CrearEmpleadoClubEscala([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string password, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ClaveEvento, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ClaveTipoColectiva, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ClaveColectivaPadre, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ClaveColectiva, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string NombreORazonSocial, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string APaterno, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string AMaterno, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Movil, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Email, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int ID_CadenaComercial, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Baja) {
            object[] results = this.Invoke("CrearEmpleadoClubEscala", new object[] {
                        usuario,
                        password,
                        ClaveEvento,
                        ClaveTipoColectiva,
                        ClaveColectivaPadre,
                        ClaveColectiva,
                        NombreORazonSocial,
                        APaterno,
                        AMaterno,
                        Movil,
                        Email,
                        ID_CadenaComercial,
                        Baja});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CrearEmpleadoClubEscalaAsync(string usuario, string password, string ClaveEvento, string ClaveTipoColectiva, string ClaveColectivaPadre, string ClaveColectiva, string NombreORazonSocial, string APaterno, string AMaterno, string Movil, string Email, int ID_CadenaComercial, string Baja) {
            this.CrearEmpleadoClubEscalaAsync(usuario, password, ClaveEvento, ClaveTipoColectiva, ClaveColectivaPadre, ClaveColectiva, NombreORazonSocial, APaterno, AMaterno, Movil, Email, ID_CadenaComercial, Baja, null);
        }
        
        /// <remarks/>
        public void CrearEmpleadoClubEscalaAsync(string usuario, string password, string ClaveEvento, string ClaveTipoColectiva, string ClaveColectivaPadre, string ClaveColectiva, string NombreORazonSocial, string APaterno, string AMaterno, string Movil, string Email, int ID_CadenaComercial, string Baja, object userState) {
            if ((this.CrearEmpleadoClubEscalaOperationCompleted == null)) {
                this.CrearEmpleadoClubEscalaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrearEmpleadoClubEscalaOperationCompleted);
            }
            this.InvokeAsync("CrearEmpleadoClubEscala", new object[] {
                        usuario,
                        password,
                        ClaveEvento,
                        ClaveTipoColectiva,
                        ClaveColectivaPadre,
                        ClaveColectiva,
                        NombreORazonSocial,
                        APaterno,
                        AMaterno,
                        Movil,
                        Email,
                        ID_CadenaComercial,
                        Baja}, this.CrearEmpleadoClubEscalaOperationCompleted, userState);
        }
        
        private void OnCrearEmpleadoClubEscalaOperationCompleted(object arg) {
            if ((this.CrearEmpleadoClubEscalaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrearEmpleadoClubEscalaCompleted(this, new CrearEmpleadoClubEscalaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://Admin/", ResponseNamespace="http://Admin/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int CrearCuentasaEmpleadoClubEscala(
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuario, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string password, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ClaveEvento, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ClaveTipoColectiva, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ClaveColectivaPadre, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ClaveColectiva, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int ID_Colectiva, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string NombreORazonSocial, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string APaterno, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string AMaterno, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string FechaNacimiento, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Movil, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Email, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ClaveGrupoMA, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string NIP, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int AniosParaExpirarMA, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ClaveGrupoCuenta, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] int ID_CadenaComercial, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ClaveTipoCuenta, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string SaldoInicial, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string Baja, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string CicloNominal, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string DiaPago) {
            object[] results = this.Invoke("CrearCuentasaEmpleadoClubEscala", new object[] {
                        usuario,
                        password,
                        ClaveEvento,
                        ClaveTipoColectiva,
                        ClaveColectivaPadre,
                        ClaveColectiva,
                        ID_Colectiva,
                        NombreORazonSocial,
                        APaterno,
                        AMaterno,
                        FechaNacimiento,
                        Movil,
                        Email,
                        ClaveGrupoMA,
                        NIP,
                        AniosParaExpirarMA,
                        ClaveGrupoCuenta,
                        ID_CadenaComercial,
                        ClaveTipoCuenta,
                        SaldoInicial,
                        Baja,
                        CicloNominal,
                        DiaPago});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void CrearCuentasaEmpleadoClubEscalaAsync(
                    string usuario, 
                    string password, 
                    string ClaveEvento, 
                    string ClaveTipoColectiva, 
                    string ClaveColectivaPadre, 
                    string ClaveColectiva, 
                    int ID_Colectiva, 
                    string NombreORazonSocial, 
                    string APaterno, 
                    string AMaterno, 
                    string FechaNacimiento, 
                    string Movil, 
                    string Email, 
                    string ClaveGrupoMA, 
                    string NIP, 
                    int AniosParaExpirarMA, 
                    string ClaveGrupoCuenta, 
                    int ID_CadenaComercial, 
                    string ClaveTipoCuenta, 
                    string SaldoInicial, 
                    string Baja, 
                    string CicloNominal, 
                    string DiaPago) {
            this.CrearCuentasaEmpleadoClubEscalaAsync(usuario, password, ClaveEvento, ClaveTipoColectiva, ClaveColectivaPadre, ClaveColectiva, ID_Colectiva, NombreORazonSocial, APaterno, AMaterno, FechaNacimiento, Movil, Email, ClaveGrupoMA, NIP, AniosParaExpirarMA, ClaveGrupoCuenta, ID_CadenaComercial, ClaveTipoCuenta, SaldoInicial, Baja, CicloNominal, DiaPago, null);
        }
        
        /// <remarks/>
        public void CrearCuentasaEmpleadoClubEscalaAsync(
                    string usuario, 
                    string password, 
                    string ClaveEvento, 
                    string ClaveTipoColectiva, 
                    string ClaveColectivaPadre, 
                    string ClaveColectiva, 
                    int ID_Colectiva, 
                    string NombreORazonSocial, 
                    string APaterno, 
                    string AMaterno, 
                    string FechaNacimiento, 
                    string Movil, 
                    string Email, 
                    string ClaveGrupoMA, 
                    string NIP, 
                    int AniosParaExpirarMA, 
                    string ClaveGrupoCuenta, 
                    int ID_CadenaComercial, 
                    string ClaveTipoCuenta, 
                    string SaldoInicial, 
                    string Baja, 
                    string CicloNominal, 
                    string DiaPago, 
                    object userState) {
            if ((this.CrearCuentasaEmpleadoClubEscalaOperationCompleted == null)) {
                this.CrearCuentasaEmpleadoClubEscalaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCrearCuentasaEmpleadoClubEscalaOperationCompleted);
            }
            this.InvokeAsync("CrearCuentasaEmpleadoClubEscala", new object[] {
                        usuario,
                        password,
                        ClaveEvento,
                        ClaveTipoColectiva,
                        ClaveColectivaPadre,
                        ClaveColectiva,
                        ID_Colectiva,
                        NombreORazonSocial,
                        APaterno,
                        AMaterno,
                        FechaNacimiento,
                        Movil,
                        Email,
                        ClaveGrupoMA,
                        NIP,
                        AniosParaExpirarMA,
                        ClaveGrupoCuenta,
                        ID_CadenaComercial,
                        ClaveTipoCuenta,
                        SaldoInicial,
                        Baja,
                        CicloNominal,
                        DiaPago}, this.CrearCuentasaEmpleadoClubEscalaOperationCompleted, userState);
        }
        
        private void OnCrearCuentasaEmpleadoClubEscalaOperationCompleted(object arg) {
            if ((this.CrearCuentasaEmpleadoClubEscalaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CrearCuentasaEmpleadoClubEscalaCompleted(this, new CrearCuentasaEmpleadoClubEscalaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ActualizaPasswordCompletedEventHandler(object sender, ActualizaPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActualizaPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ActualizaPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GeneraCorteOperadorCompletedEventHandler(object sender, GeneraCorteOperadorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GeneraCorteOperadorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GeneraCorteOperadorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ObtieneDetallesCorteOperadorCompletedEventHandler(object sender, ObtieneDetallesCorteOperadorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtieneDetallesCorteOperadorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtieneDetallesCorteOperadorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void EnviaSMSCompletedEventHandler(object sender, EnviaSMSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviaSMSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviaSMSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CrearEmpleadoClubEscalaCompletedEventHandler(object sender, CrearEmpleadoClubEscalaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrearEmpleadoClubEscalaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CrearEmpleadoClubEscalaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CrearCuentasaEmpleadoClubEscalaCompletedEventHandler(object sender, CrearCuentasaEmpleadoClubEscalaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CrearCuentasaEmpleadoClubEscalaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CrearCuentasaEmpleadoClubEscalaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591