# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest # Utilizar un entorno windows para generar un ejecutable, ya que en linux no se produce un ejecutable al compilar 

    steps:
    - uses: actions/checkout@v4 # Revisar el contenido del repositorio
    #- name: Setup .NET
     # uses: actions/setup-dotnet@v4 # Instalar .NET para el uso ded comandos como dotnet build o restore
      #with:
        #dotnet-version: 4.6.X
    - name: Ubicar y listar directorio
      run: |
          cd D:\a\prueba\prueba\ElProcesador\Core\Procesador
          ls
    #- name: Build
     # run: dotnet build D:\a\prueba\prueba\ElProcesador\Core\Procesador\Procesador.csproj --no-restore --configuration Release # La bandera --no-restore es porque se especifica en la línea superior que se restauren las dependencias y el comando build las restaura implícitamente

    - name: Descargar instalador de .NET Framework 4.6.1
      run: |
          Invoke-WebRequest -Uri "https://download.microsoft.com/download/7/8/3/783F3D2A-8F7D-4C6E-9F6C-8A6F7C1C1C1C/NDP461-KB3102436-x86-x64-AllOS-ENU.exe" -OutFile "NDP461-KB3102436-x86-x64-AllOS-ENU.exe"

    - name: Instalar .NET Framework 4.6.1
      run: |
          Start-Process -FilePath ".\NDP461-KB3102436-x86-x64-AllOS-ENU.exe" -ArgumentList "/quiet", "/norestart" -Wait

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build app for release
      run: msbuild D:\a\prueba\prueba\ElProcesador\Core\Procesador\Procesador.csproj -t:rebuild -verbosity:diag -property:Configuration=Release

    #- name: Subir Artefactos  
     # uses: actions/upload-artifact@v4  # Subir los archivos del directorio a un artefacto
      #with:
       # name: Archivos Compilados
        #path: D:\a\prueba\prueba\ElProcesador\Core\Procesador\bin\Release\net8.0\
