//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace DNU_ProcesadorGenerico.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PaymentProcessPortBinding", Namespace="http://ws.wscomponent.com/")]
    public partial class PaymentProcess : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback NewAccountOperationCompleted;
        
        private System.Threading.SendOrPostCallback FullBalanceRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback PhoneRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback PayOperationCompleted;
        
        private System.Threading.SendOrPostCallback PayValidationOperationCompleted;
        
        private System.Threading.SendOrPostCallback PayCancellationOperationCompleted;
        
        private System.Threading.SendOrPostCallback BalanceRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback RewardOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PaymentProcess() {
            this.Url = global::DNU_ProcesadorGenerico.Properties.Settings.Default.DNU_ProcesadorGenerico_WebReference_PaymentProcess;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event NewAccountCompletedEventHandler NewAccountCompleted;
        
        /// <remarks/>
        public event FullBalanceRequestCompletedEventHandler FullBalanceRequestCompleted;
        
        /// <remarks/>
        public event PhoneRequestCompletedEventHandler PhoneRequestCompleted;
        
        /// <remarks/>
        public event PayCompletedEventHandler PayCompleted;
        
        /// <remarks/>
        public event PayValidationCompletedEventHandler PayValidationCompleted;
        
        /// <remarks/>
        public event PayCancellationCompletedEventHandler PayCancellationCompleted;
        
        /// <remarks/>
        public event BalanceRequestCompletedEventHandler BalanceRequestCompleted;
        
        /// <remarks/>
        public event RewardCompletedEventHandler RewardCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.wscomponent.com/", ResponseNamespace="http://ws.wscomponent.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public myNewAccountResponse NewAccount([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Password, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _TipoMedioPago, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _MedioPago, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _SKU_Beneficio, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Fecha, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Hora, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Sucursal, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Afiliacion, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Terminal) {
            object[] results = this.Invoke("NewAccount", new object[] {
                        _Usuario,
                        _Password,
                        _TipoMedioPago,
                        _MedioPago,
                        _SKU_Beneficio,
                        _Fecha,
                        _Hora,
                        _Sucursal,
                        _Afiliacion,
                        _Terminal});
            return ((myNewAccountResponse)(results[0]));
        }
        
        /// <remarks/>
        public void NewAccountAsync(string _Usuario, string _Password, string _TipoMedioPago, string _MedioPago, string _SKU_Beneficio, string _Fecha, string _Hora, string _Sucursal, string _Afiliacion, string _Terminal) {
            this.NewAccountAsync(_Usuario, _Password, _TipoMedioPago, _MedioPago, _SKU_Beneficio, _Fecha, _Hora, _Sucursal, _Afiliacion, _Terminal, null);
        }
        
        /// <remarks/>
        public void NewAccountAsync(string _Usuario, string _Password, string _TipoMedioPago, string _MedioPago, string _SKU_Beneficio, string _Fecha, string _Hora, string _Sucursal, string _Afiliacion, string _Terminal, object userState) {
            if ((this.NewAccountOperationCompleted == null)) {
                this.NewAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNewAccountOperationCompleted);
            }
            this.InvokeAsync("NewAccount", new object[] {
                        _Usuario,
                        _Password,
                        _TipoMedioPago,
                        _MedioPago,
                        _SKU_Beneficio,
                        _Fecha,
                        _Hora,
                        _Sucursal,
                        _Afiliacion,
                        _Terminal}, this.NewAccountOperationCompleted, userState);
        }
        
        private void OnNewAccountOperationCompleted(object arg) {
            if ((this.NewAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NewAccountCompleted(this, new NewAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.wscomponent.com/", ResponseNamespace="http://ws.wscomponent.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public myFullBalanceResponse FullBalanceRequest([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Password, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _MedioPago, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _TipoMedioPago, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Expiracion, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _CodigoValidacion, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Sucursal, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Afiliacion, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Terminal, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Operador) {
            object[] results = this.Invoke("FullBalanceRequest", new object[] {
                        _Usuario,
                        _Password,
                        _MedioPago,
                        _TipoMedioPago,
                        _Expiracion,
                        _CodigoValidacion,
                        _Sucursal,
                        _Afiliacion,
                        _Terminal,
                        _Operador});
            return ((myFullBalanceResponse)(results[0]));
        }
        
        /// <remarks/>
        public void FullBalanceRequestAsync(string _Usuario, string _Password, string _MedioPago, string _TipoMedioPago, string _Expiracion, string _CodigoValidacion, string _Sucursal, string _Afiliacion, string _Terminal, string _Operador) {
            this.FullBalanceRequestAsync(_Usuario, _Password, _MedioPago, _TipoMedioPago, _Expiracion, _CodigoValidacion, _Sucursal, _Afiliacion, _Terminal, _Operador, null);
        }
        
        /// <remarks/>
        public void FullBalanceRequestAsync(string _Usuario, string _Password, string _MedioPago, string _TipoMedioPago, string _Expiracion, string _CodigoValidacion, string _Sucursal, string _Afiliacion, string _Terminal, string _Operador, object userState) {
            if ((this.FullBalanceRequestOperationCompleted == null)) {
                this.FullBalanceRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFullBalanceRequestOperationCompleted);
            }
            this.InvokeAsync("FullBalanceRequest", new object[] {
                        _Usuario,
                        _Password,
                        _MedioPago,
                        _TipoMedioPago,
                        _Expiracion,
                        _CodigoValidacion,
                        _Sucursal,
                        _Afiliacion,
                        _Terminal,
                        _Operador}, this.FullBalanceRequestOperationCompleted, userState);
        }
        
        private void OnFullBalanceRequestOperationCompleted(object arg) {
            if ((this.FullBalanceRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FullBalanceRequestCompleted(this, new FullBalanceRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.wscomponent.com/", ResponseNamespace="http://ws.wscomponent.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public myPhoneResponse PhoneRequest([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Password, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _TipoMedioPago, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _MedioPago, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string GeneraCodigo) {
            object[] results = this.Invoke("PhoneRequest", new object[] {
                        _Usuario,
                        _Password,
                        _TipoMedioPago,
                        _MedioPago,
                        GeneraCodigo});
            return ((myPhoneResponse)(results[0]));
        }
        
        /// <remarks/>
        public void PhoneRequestAsync(string _Usuario, string _Password, string _TipoMedioPago, string _MedioPago, string GeneraCodigo) {
            this.PhoneRequestAsync(_Usuario, _Password, _TipoMedioPago, _MedioPago, GeneraCodigo, null);
        }
        
        /// <remarks/>
        public void PhoneRequestAsync(string _Usuario, string _Password, string _TipoMedioPago, string _MedioPago, string GeneraCodigo, object userState) {
            if ((this.PhoneRequestOperationCompleted == null)) {
                this.PhoneRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPhoneRequestOperationCompleted);
            }
            this.InvokeAsync("PhoneRequest", new object[] {
                        _Usuario,
                        _Password,
                        _TipoMedioPago,
                        _MedioPago,
                        GeneraCodigo}, this.PhoneRequestOperationCompleted, userState);
        }
        
        private void OnPhoneRequestOperationCompleted(object arg) {
            if ((this.PhoneRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PhoneRequestCompleted(this, new PhoneRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.wscomponent.com/", ResponseNamespace="http://ws.wscomponent.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public myPayResponse Pay(
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Usuario, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Password, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _TipoMedioPago, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _MedioPago, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Sufijo, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Token, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Expiracion, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _CodigoValidacion, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _SKU_Beneficio, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] float _Importe, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] float _ImporteDescuento, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Fecha, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Hora, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Ticket, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Sucursal, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Afiliacion, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Terminal, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Operador, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _SKUS) {
            object[] results = this.Invoke("Pay", new object[] {
                        _Usuario,
                        _Password,
                        _TipoMedioPago,
                        _MedioPago,
                        _Sufijo,
                        _Token,
                        _Expiracion,
                        _CodigoValidacion,
                        _SKU_Beneficio,
                        _Importe,
                        _ImporteDescuento,
                        _Fecha,
                        _Hora,
                        _Ticket,
                        _Sucursal,
                        _Afiliacion,
                        _Terminal,
                        _Operador,
                        _SKUS});
            return ((myPayResponse)(results[0]));
        }
        
        /// <remarks/>
        public void PayAsync(
                    string _Usuario, 
                    string _Password, 
                    string _TipoMedioPago, 
                    string _MedioPago, 
                    string _Sufijo, 
                    string _Token, 
                    string _Expiracion, 
                    string _CodigoValidacion, 
                    string _SKU_Beneficio, 
                    float _Importe, 
                    float _ImporteDescuento, 
                    string _Fecha, 
                    string _Hora, 
                    string _Ticket, 
                    string _Sucursal, 
                    string _Afiliacion, 
                    string _Terminal, 
                    string _Operador, 
                    string _SKUS) {
            this.PayAsync(_Usuario, _Password, _TipoMedioPago, _MedioPago, _Sufijo, _Token, _Expiracion, _CodigoValidacion, _SKU_Beneficio, _Importe, _ImporteDescuento, _Fecha, _Hora, _Ticket, _Sucursal, _Afiliacion, _Terminal, _Operador, _SKUS, null);
        }
        
        /// <remarks/>
        public void PayAsync(
                    string _Usuario, 
                    string _Password, 
                    string _TipoMedioPago, 
                    string _MedioPago, 
                    string _Sufijo, 
                    string _Token, 
                    string _Expiracion, 
                    string _CodigoValidacion, 
                    string _SKU_Beneficio, 
                    float _Importe, 
                    float _ImporteDescuento, 
                    string _Fecha, 
                    string _Hora, 
                    string _Ticket, 
                    string _Sucursal, 
                    string _Afiliacion, 
                    string _Terminal, 
                    string _Operador, 
                    string _SKUS, 
                    object userState) {
            if ((this.PayOperationCompleted == null)) {
                this.PayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPayOperationCompleted);
            }
            this.InvokeAsync("Pay", new object[] {
                        _Usuario,
                        _Password,
                        _TipoMedioPago,
                        _MedioPago,
                        _Sufijo,
                        _Token,
                        _Expiracion,
                        _CodigoValidacion,
                        _SKU_Beneficio,
                        _Importe,
                        _ImporteDescuento,
                        _Fecha,
                        _Hora,
                        _Ticket,
                        _Sucursal,
                        _Afiliacion,
                        _Terminal,
                        _Operador,
                        _SKUS}, this.PayOperationCompleted, userState);
        }
        
        private void OnPayOperationCompleted(object arg) {
            if ((this.PayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PayCompleted(this, new PayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.wscomponent.com/", ResponseNamespace="http://ws.wscomponent.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public myPayValidationResponse PayValidation(
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Usuario, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Password, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _MedioPago, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _TipoMedioPago, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Expiracion, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _CodigoValidacion, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _SKU_Beneficio, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] float _Importe, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] float _ImporteDescuento, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Fecha, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Hora, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Ticket, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Sucursal, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Afiliacion, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Terminal, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Operador) {
            object[] results = this.Invoke("PayValidation", new object[] {
                        _Usuario,
                        _Password,
                        _MedioPago,
                        _TipoMedioPago,
                        _Expiracion,
                        _CodigoValidacion,
                        _SKU_Beneficio,
                        _Importe,
                        _ImporteDescuento,
                        _Fecha,
                        _Hora,
                        _Ticket,
                        _Sucursal,
                        _Afiliacion,
                        _Terminal,
                        _Operador});
            return ((myPayValidationResponse)(results[0]));
        }
        
        /// <remarks/>
        public void PayValidationAsync(
                    string _Usuario, 
                    string _Password, 
                    string _MedioPago, 
                    string _TipoMedioPago, 
                    string _Expiracion, 
                    string _CodigoValidacion, 
                    string _SKU_Beneficio, 
                    float _Importe, 
                    float _ImporteDescuento, 
                    string _Fecha, 
                    string _Hora, 
                    string _Ticket, 
                    string _Sucursal, 
                    string _Afiliacion, 
                    string _Terminal, 
                    string _Operador) {
            this.PayValidationAsync(_Usuario, _Password, _MedioPago, _TipoMedioPago, _Expiracion, _CodigoValidacion, _SKU_Beneficio, _Importe, _ImporteDescuento, _Fecha, _Hora, _Ticket, _Sucursal, _Afiliacion, _Terminal, _Operador, null);
        }
        
        /// <remarks/>
        public void PayValidationAsync(
                    string _Usuario, 
                    string _Password, 
                    string _MedioPago, 
                    string _TipoMedioPago, 
                    string _Expiracion, 
                    string _CodigoValidacion, 
                    string _SKU_Beneficio, 
                    float _Importe, 
                    float _ImporteDescuento, 
                    string _Fecha, 
                    string _Hora, 
                    string _Ticket, 
                    string _Sucursal, 
                    string _Afiliacion, 
                    string _Terminal, 
                    string _Operador, 
                    object userState) {
            if ((this.PayValidationOperationCompleted == null)) {
                this.PayValidationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPayValidationOperationCompleted);
            }
            this.InvokeAsync("PayValidation", new object[] {
                        _Usuario,
                        _Password,
                        _MedioPago,
                        _TipoMedioPago,
                        _Expiracion,
                        _CodigoValidacion,
                        _SKU_Beneficio,
                        _Importe,
                        _ImporteDescuento,
                        _Fecha,
                        _Hora,
                        _Ticket,
                        _Sucursal,
                        _Afiliacion,
                        _Terminal,
                        _Operador}, this.PayValidationOperationCompleted, userState);
        }
        
        private void OnPayValidationOperationCompleted(object arg) {
            if ((this.PayValidationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PayValidationCompleted(this, new PayValidationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.wscomponent.com/", ResponseNamespace="http://ws.wscomponent.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public myPayCancellationResponse PayCancellation(
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Usuario, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Password, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _MedioPago, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _TipoMedioPago, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Sufijo, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Expiracion, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _CodigoValidacion, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _SKU_Beneficio, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] float _Importe, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] float _ImporteDescuento, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Autorizacion, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Fecha, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Hora, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Ticket, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Sucursal, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Afiliacion, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Terminal, 
                    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Operador) {
            object[] results = this.Invoke("PayCancellation", new object[] {
                        _Usuario,
                        _Password,
                        _MedioPago,
                        _TipoMedioPago,
                        _Sufijo,
                        _Expiracion,
                        _CodigoValidacion,
                        _SKU_Beneficio,
                        _Importe,
                        _ImporteDescuento,
                        _Autorizacion,
                        _Fecha,
                        _Hora,
                        _Ticket,
                        _Sucursal,
                        _Afiliacion,
                        _Terminal,
                        _Operador});
            return ((myPayCancellationResponse)(results[0]));
        }
        
        /// <remarks/>
        public void PayCancellationAsync(
                    string _Usuario, 
                    string _Password, 
                    string _MedioPago, 
                    string _TipoMedioPago, 
                    string _Sufijo, 
                    string _Expiracion, 
                    string _CodigoValidacion, 
                    string _SKU_Beneficio, 
                    float _Importe, 
                    float _ImporteDescuento, 
                    string _Autorizacion, 
                    string _Fecha, 
                    string _Hora, 
                    string _Ticket, 
                    string _Sucursal, 
                    string _Afiliacion, 
                    string _Terminal, 
                    string _Operador) {
            this.PayCancellationAsync(_Usuario, _Password, _MedioPago, _TipoMedioPago, _Sufijo, _Expiracion, _CodigoValidacion, _SKU_Beneficio, _Importe, _ImporteDescuento, _Autorizacion, _Fecha, _Hora, _Ticket, _Sucursal, _Afiliacion, _Terminal, _Operador, null);
        }
        
        /// <remarks/>
        public void PayCancellationAsync(
                    string _Usuario, 
                    string _Password, 
                    string _MedioPago, 
                    string _TipoMedioPago, 
                    string _Sufijo, 
                    string _Expiracion, 
                    string _CodigoValidacion, 
                    string _SKU_Beneficio, 
                    float _Importe, 
                    float _ImporteDescuento, 
                    string _Autorizacion, 
                    string _Fecha, 
                    string _Hora, 
                    string _Ticket, 
                    string _Sucursal, 
                    string _Afiliacion, 
                    string _Terminal, 
                    string _Operador, 
                    object userState) {
            if ((this.PayCancellationOperationCompleted == null)) {
                this.PayCancellationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPayCancellationOperationCompleted);
            }
            this.InvokeAsync("PayCancellation", new object[] {
                        _Usuario,
                        _Password,
                        _MedioPago,
                        _TipoMedioPago,
                        _Sufijo,
                        _Expiracion,
                        _CodigoValidacion,
                        _SKU_Beneficio,
                        _Importe,
                        _ImporteDescuento,
                        _Autorizacion,
                        _Fecha,
                        _Hora,
                        _Ticket,
                        _Sucursal,
                        _Afiliacion,
                        _Terminal,
                        _Operador}, this.PayCancellationOperationCompleted, userState);
        }
        
        private void OnPayCancellationOperationCompleted(object arg) {
            if ((this.PayCancellationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PayCancellationCompleted(this, new PayCancellationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.wscomponent.com/", ResponseNamespace="http://ws.wscomponent.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public myBalanceResponse BalanceRequest([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Password, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _MedioPago, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _TipoMedioPago, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Expiracion, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _CodigoValidacion, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _SKU_Beneficio, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Sucursal, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Afiliacion, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Terminal, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Operador) {
            object[] results = this.Invoke("BalanceRequest", new object[] {
                        _Usuario,
                        _Password,
                        _MedioPago,
                        _TipoMedioPago,
                        _Expiracion,
                        _CodigoValidacion,
                        _SKU_Beneficio,
                        _Sucursal,
                        _Afiliacion,
                        _Terminal,
                        _Operador});
            return ((myBalanceResponse)(results[0]));
        }
        
        /// <remarks/>
        public void BalanceRequestAsync(string _Usuario, string _Password, string _MedioPago, string _TipoMedioPago, string _Expiracion, string _CodigoValidacion, string _SKU_Beneficio, string _Sucursal, string _Afiliacion, string _Terminal, string _Operador) {
            this.BalanceRequestAsync(_Usuario, _Password, _MedioPago, _TipoMedioPago, _Expiracion, _CodigoValidacion, _SKU_Beneficio, _Sucursal, _Afiliacion, _Terminal, _Operador, null);
        }
        
        /// <remarks/>
        public void BalanceRequestAsync(string _Usuario, string _Password, string _MedioPago, string _TipoMedioPago, string _Expiracion, string _CodigoValidacion, string _SKU_Beneficio, string _Sucursal, string _Afiliacion, string _Terminal, string _Operador, object userState) {
            if ((this.BalanceRequestOperationCompleted == null)) {
                this.BalanceRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBalanceRequestOperationCompleted);
            }
            this.InvokeAsync("BalanceRequest", new object[] {
                        _Usuario,
                        _Password,
                        _MedioPago,
                        _TipoMedioPago,
                        _Expiracion,
                        _CodigoValidacion,
                        _SKU_Beneficio,
                        _Sucursal,
                        _Afiliacion,
                        _Terminal,
                        _Operador}, this.BalanceRequestOperationCompleted, userState);
        }
        
        private void OnBalanceRequestOperationCompleted(object arg) {
            if ((this.BalanceRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BalanceRequestCompleted(this, new BalanceRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://ws.wscomponent.com/", ResponseNamespace="http://ws.wscomponent.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public myRewardResponse Reward([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Password, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _MedioPago, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _TipoMedioPago, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _SKU_Beneficio, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] float _Importe, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Ticket, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Sucursal, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Afiliacion, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Terminal, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _Operador, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string _SKUS) {
            object[] results = this.Invoke("Reward", new object[] {
                        _Usuario,
                        _Password,
                        _MedioPago,
                        _TipoMedioPago,
                        _SKU_Beneficio,
                        _Importe,
                        _Ticket,
                        _Sucursal,
                        _Afiliacion,
                        _Terminal,
                        _Operador,
                        _SKUS});
            return ((myRewardResponse)(results[0]));
        }
        
        /// <remarks/>
        public void RewardAsync(string _Usuario, string _Password, string _MedioPago, string _TipoMedioPago, string _SKU_Beneficio, float _Importe, string _Ticket, string _Sucursal, string _Afiliacion, string _Terminal, string _Operador, string _SKUS) {
            this.RewardAsync(_Usuario, _Password, _MedioPago, _TipoMedioPago, _SKU_Beneficio, _Importe, _Ticket, _Sucursal, _Afiliacion, _Terminal, _Operador, _SKUS, null);
        }
        
        /// <remarks/>
        public void RewardAsync(string _Usuario, string _Password, string _MedioPago, string _TipoMedioPago, string _SKU_Beneficio, float _Importe, string _Ticket, string _Sucursal, string _Afiliacion, string _Terminal, string _Operador, string _SKUS, object userState) {
            if ((this.RewardOperationCompleted == null)) {
                this.RewardOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRewardOperationCompleted);
            }
            this.InvokeAsync("Reward", new object[] {
                        _Usuario,
                        _Password,
                        _MedioPago,
                        _TipoMedioPago,
                        _SKU_Beneficio,
                        _Importe,
                        _Ticket,
                        _Sucursal,
                        _Afiliacion,
                        _Terminal,
                        _Operador,
                        _SKUS}, this.RewardOperationCompleted, userState);
        }
        
        private void OnRewardOperationCompleted(object arg) {
            if ((this.RewardCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RewardCompleted(this, new RewardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1649.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.wscomponent.com/")]
    public partial class myNewAccountResponse {
        
        private string autorizacionField;
        
        private string codigoRespuestaField;
        
        private string descripcionField;
        
        private string numCuentaField;
        
        private string numTarjetaField;
        
        private string terminalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string autorizacion {
            get {
                return this.autorizacionField;
            }
            set {
                this.autorizacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoRespuesta {
            get {
                return this.codigoRespuestaField;
            }
            set {
                this.codigoRespuestaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numCuenta {
            get {
                return this.numCuentaField;
            }
            set {
                this.numCuentaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numTarjeta {
            get {
                return this.numTarjetaField;
            }
            set {
                this.numTarjetaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string terminal {
            get {
                return this.terminalField;
            }
            set {
                this.terminalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1649.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.wscomponent.com/")]
    public partial class myRewardResponse {
        
        private string autorizacionField;
        
        private string beneficiosField;
        
        private int codigoRespuestaField;
        
        private string descripcionField;
        
        private string leyendaField;
        
        private string saldosField;
        
        private string terminalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string autorizacion {
            get {
                return this.autorizacionField;
            }
            set {
                this.autorizacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string beneficios {
            get {
                return this.beneficiosField;
            }
            set {
                this.beneficiosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigoRespuesta {
            get {
                return this.codigoRespuestaField;
            }
            set {
                this.codigoRespuestaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string leyenda {
            get {
                return this.leyendaField;
            }
            set {
                this.leyendaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string saldos {
            get {
                return this.saldosField;
            }
            set {
                this.saldosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string terminal {
            get {
                return this.terminalField;
            }
            set {
                this.terminalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1649.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.wscomponent.com/")]
    public partial class myBalanceResponse {
        
        private string autorizacionField;
        
        private string codigoRespuestaField;
        
        private string descripcionField;
        
        private string leyendaField;
        
        private float otroSaldoField;
        
        private float saldoPesosField;
        
        private string terminalField;
        
        private string unidadOtroSaldoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string autorizacion {
            get {
                return this.autorizacionField;
            }
            set {
                this.autorizacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoRespuesta {
            get {
                return this.codigoRespuestaField;
            }
            set {
                this.codigoRespuestaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string leyenda {
            get {
                return this.leyendaField;
            }
            set {
                this.leyendaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float otroSaldo {
            get {
                return this.otroSaldoField;
            }
            set {
                this.otroSaldoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float saldoPesos {
            get {
                return this.saldoPesosField;
            }
            set {
                this.saldoPesosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string terminal {
            get {
                return this.terminalField;
            }
            set {
                this.terminalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string unidadOtroSaldo {
            get {
                return this.unidadOtroSaldoField;
            }
            set {
                this.unidadOtroSaldoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1649.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.wscomponent.com/")]
    public partial class myPayCancellationResponse {
        
        private string autorizacionField;
        
        private string codigoRespuestaField;
        
        private string descripcionField;
        
        private string leyendaField;
        
        private float saldoPesosField;
        
        private float saldoPuntosField;
        
        private string terminalField;
        
        private string ticketField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string autorizacion {
            get {
                return this.autorizacionField;
            }
            set {
                this.autorizacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoRespuesta {
            get {
                return this.codigoRespuestaField;
            }
            set {
                this.codigoRespuestaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string leyenda {
            get {
                return this.leyendaField;
            }
            set {
                this.leyendaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float saldoPesos {
            get {
                return this.saldoPesosField;
            }
            set {
                this.saldoPesosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float saldoPuntos {
            get {
                return this.saldoPuntosField;
            }
            set {
                this.saldoPuntosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string terminal {
            get {
                return this.terminalField;
            }
            set {
                this.terminalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ticket {
            get {
                return this.ticketField;
            }
            set {
                this.ticketField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1649.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.wscomponent.com/")]
    public partial class myPayValidationResponse {
        
        private string autorizacionField;
        
        private string codigoRespuestaField;
        
        private string descripcionField;
        
        private float importeAplicadoField;
        
        private string leyendaField;
        
        private float otroSaldoField;
        
        private string sKUsField;
        
        private float saldoPesosField;
        
        private string terminalField;
        
        private string ticketField;
        
        private string unidadOtroSaldoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string autorizacion {
            get {
                return this.autorizacionField;
            }
            set {
                this.autorizacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoRespuesta {
            get {
                return this.codigoRespuestaField;
            }
            set {
                this.codigoRespuestaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float importeAplicado {
            get {
                return this.importeAplicadoField;
            }
            set {
                this.importeAplicadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string leyenda {
            get {
                return this.leyendaField;
            }
            set {
                this.leyendaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float otroSaldo {
            get {
                return this.otroSaldoField;
            }
            set {
                this.otroSaldoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SKUs {
            get {
                return this.sKUsField;
            }
            set {
                this.sKUsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float saldoPesos {
            get {
                return this.saldoPesosField;
            }
            set {
                this.saldoPesosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string terminal {
            get {
                return this.terminalField;
            }
            set {
                this.terminalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ticket {
            get {
                return this.ticketField;
            }
            set {
                this.ticketField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string unidadOtroSaldo {
            get {
                return this.unidadOtroSaldoField;
            }
            set {
                this.unidadOtroSaldoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1649.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.wscomponent.com/")]
    public partial class myPayResponse {
        
        private string autorizacionField;
        
        private string codigoRespuestaField;
        
        private string descripcionField;
        
        private float importeAplicadoField;
        
        private string leyendaField;
        
        private float otroSaldoField;
        
        private string sKUsField;
        
        private float saldoPesosField;
        
        private string terminalField;
        
        private string ticketField;
        
        private string unidadOtroSaldoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string autorizacion {
            get {
                return this.autorizacionField;
            }
            set {
                this.autorizacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoRespuesta {
            get {
                return this.codigoRespuestaField;
            }
            set {
                this.codigoRespuestaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float importeAplicado {
            get {
                return this.importeAplicadoField;
            }
            set {
                this.importeAplicadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string leyenda {
            get {
                return this.leyendaField;
            }
            set {
                this.leyendaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float otroSaldo {
            get {
                return this.otroSaldoField;
            }
            set {
                this.otroSaldoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SKUs {
            get {
                return this.sKUsField;
            }
            set {
                this.sKUsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float saldoPesos {
            get {
                return this.saldoPesosField;
            }
            set {
                this.saldoPesosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string terminal {
            get {
                return this.terminalField;
            }
            set {
                this.terminalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ticket {
            get {
                return this.ticketField;
            }
            set {
                this.ticketField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string unidadOtroSaldo {
            get {
                return this.unidadOtroSaldoField;
            }
            set {
                this.unidadOtroSaldoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1649.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.wscomponent.com/")]
    public partial class myPhoneResponse {
        
        private int codigoRespuestaField;
        
        private string codigoValidacionField;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigoRespuesta {
            get {
                return this.codigoRespuestaField;
            }
            set {
                this.codigoRespuestaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoValidacion {
            get {
                return this.codigoValidacionField;
            }
            set {
                this.codigoValidacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1649.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.wscomponent.com/")]
    public partial class myFullBalanceResponse {
        
        private string autorizacionField;
        
        private int codigoRespuestaField;
        
        private string descripcionField;
        
        private string leyendaField;
        
        private string terminalField;
        
        private string xmlSaldosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string autorizacion {
            get {
                return this.autorizacionField;
            }
            set {
                this.autorizacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int codigoRespuesta {
            get {
                return this.codigoRespuestaField;
            }
            set {
                this.codigoRespuestaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string leyenda {
            get {
                return this.leyendaField;
            }
            set {
                this.leyendaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string terminal {
            get {
                return this.terminalField;
            }
            set {
                this.terminalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string xmlSaldos {
            get {
                return this.xmlSaldosField;
            }
            set {
                this.xmlSaldosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void NewAccountCompletedEventHandler(object sender, NewAccountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NewAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NewAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public myNewAccountResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((myNewAccountResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void FullBalanceRequestCompletedEventHandler(object sender, FullBalanceRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FullBalanceRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FullBalanceRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public myFullBalanceResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((myFullBalanceResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void PhoneRequestCompletedEventHandler(object sender, PhoneRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PhoneRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PhoneRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public myPhoneResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((myPhoneResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void PayCompletedEventHandler(object sender, PayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public myPayResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((myPayResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void PayValidationCompletedEventHandler(object sender, PayValidationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PayValidationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PayValidationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public myPayValidationResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((myPayValidationResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void PayCancellationCompletedEventHandler(object sender, PayCancellationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PayCancellationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PayCancellationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public myPayCancellationResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((myPayCancellationResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void BalanceRequestCompletedEventHandler(object sender, BalanceRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BalanceRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BalanceRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public myBalanceResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((myBalanceResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    public delegate void RewardCompletedEventHandler(object sender, RewardCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1099.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RewardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RewardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public myRewardResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((myRewardResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591